/**
 * Custom worker entry — re-exports the OpenNext-generated fetch handler and
 * adds a daily `scheduled` retention purge for the telemetry D1 table.
 *
 * The generated `.open-next/worker.js` only exports a `fetch` handler, so a
 * wrapper entry is required to expose Cloudflare Cron Triggers.
 * See https://opennext.js.org/cloudflare/howtos/custom-worker
 *
 * This file is deliberately `.mjs` so it is not pulled into the Next app's
 * tsc/eslint program (the generated worker it wraps uses `@ts-expect-error`
 * against build-only modules).
 */

// @ts-ignore `.open-next/worker.js` is generated by `pnpm cf:build`
import { default as handler } from "./.open-next/worker.js";

const RETENTION_DAYS = 365;
const DAY_MS = 24 * 60 * 60 * 1000;

export default {
  fetch: handler.fetch,

  async scheduled(_event, env, _ctx) {
    const db = env && env.TELEMETRY_DB;
    if (!db) {
      console.error("[retention] TELEMETRY_DB binding missing — skipping purge");
      return;
    }
    const cutoffMs = Date.now() - RETENTION_DAYS * DAY_MS;
    try {
      const result = await db
        .prepare("DELETE FROM telemetry_events WHERE ts < ?")
        .bind(cutoffMs)
        .run();
      console.log(
        `[retention] purged ${result.meta.changes} telemetry_events older than ${RETENTION_DAYS} days`,
      );
    } catch (err) {
      console.error("[retention] purge failed", err);
    }
  },
};

// Re-export Durable Objects only if your app uses the DO Queue / tag cache.
// The D1-backed store below does not, so we deliberately do not re-export them.