tools:
    shell:
        allow:
            - ls *
            - find *
            - head *
            - Get-ChildItem *
            - Select-Object FullName
            - Where-Object { *
            - cd *
            - git log *
            - Select-Object *
            - git show *
            - node *
            - Select-String *
            - npx tsc *
            - Get-Content *
            - ForEach-Object { Select-String *
            - npm install expo-linear-gradient *
            - pnpm add expo-linear-gradient *
            - sleep 10
            - sleep 15
            - sleep 30
            - Sort-Object Length *
            - Sort-Object
            - Sort-Object FullName
