import React, {
  useRef,
  useState,
  useCallback,
  useMemo,
  useEffect,
} from "react";
import {
  View,
  Text,
  TouchableOpacity,
  ActivityIndicator,
  Dimensions,
  Animated,
  Platform,
  Modal,
  ScrollView,
  AppState,
} from "react-native";
import { colors } from "../theme/colors";
import { ProgressiveImage } from "./ProgressiveImage";
import PlayerWebView, { PlayerWebViewRef } from "../modules/player-webview";
import { Ionicons } from "@expo/vector-icons";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import {
  getNonAnimeProviders,
  getEnabledProviders,
  filterAnimeProviders,
  getProvidersForMode,
  getImageUrl,
  isSkipIntroEnabled,
  isUiEnabled,
  getProgressMode,
  getResumeMode,
  buildAllScriptsWithScriptlets,
  DEVTOOL_CONSOLE_MASK_SCRIPT,
  PlaybackEngine,
  buildEpisodeKey,
  MEDIA_HOOK_SCRIPT,
} from "@filmsnaps/shared";
import { malToAni, resolveShow } from "../lib/anime/resolve";
import type { ProviderDefinition } from "@filmsnaps/shared";
import * as ScreenOrientation from "expo-screen-orientation";
import { useKeepAwake } from "expo-keep-awake";
import AsyncStorage from "@react-native-async-storage/async-storage";
import {
  saveProgress,
  getResumePoint,
  getProgress,
  markCompleted,
} from "../lib/watchHistory";
import { fetchIntroSegments, getActiveSkipSegment } from "../lib/introDetect";
import type { IntroDbResponse } from "../lib/introDetect";
import { tmdbApi } from "../lib/api";
import { getNextEpisode } from "../lib/tvUtils";
import { clearAllState, getConfigVersion } from "../modules/player-webview";
import { providerConfigs, generateProviderSnippet } from "./providerConfig";
import { PlayerControlOverlay } from "./player/PlayerControlOverlay";
import { EpisodeRail } from "./player/EpisodeRail";
import { ServerPickerSheet } from "./player/ServerPickerSheet";
import { ServerNotes } from "./player/ServerNotes";
import { useSettings } from "../lib/settings";

// â”€â”€ Guard scripts â”€â”€ injected via shared package â”€â”€
// Generated by buildAllScriptsWithScriptlets() from @filmsnaps/shared:
//   - 15-layer popup/ad-blocking guard (buildGuardScript)
//   - uBlock Origin anti-anti-adblock scriptlets
//   - Content-ready detection + progress bridge
//   - Provider-specific cosmetic CSS (from providerConfig.ts)

function makeConsolidatedScript(
  providerHost: string,
  providerId?: string,
  skipGuard?: boolean,
): string {
  const providerConfig = providerId ? providerConfigs[providerId] : undefined;

  // DIAGNOSTIC (ad-suppression expert consult V2 §2.3): log whether the
  // 4th arg (apiIntercepts) is actually reaching the shared bundle. If this
  // logs UNDEFINED, the intercept rule set is empty in the injected JS and
  // the /api/ads/cycles poll can never be matched.
  const apiIntercepts = providerConfig?.apiIntercepts;
  console.log(
    `[VideoWebView] apiIntercepts for ${providerId ?? "null"}: ${
      apiIntercepts ? `${apiIntercepts.length} rules` : "UNDEFINED"
    }`,
  );

  // Start with shared guard + uBO scriptlets. Pass the provider's synthetic
  // API intercepts (screenscape's /api/ads/cycles ad-window poll) so the
  // fetch/XHR monkey-patch returns a synthetic response before the request
  // leaves the WebView — Level-2 parity with desktop.
  //
  // IMPORTANT (expert review): the 3rd arg (blockedDomains) is intentionally
  // EMPTY. Domain/network blocking belongs in the NATIVE engine
  // (shouldInterceptRequest → AdblockEngine + R6 domain-blocklist), which is
  // faster, lower-memory, and cannot be bypassed by a JS fetch()/XHR polyfill.
  // Keeping a second hardcoded JS blocklist would (a) miss OTA filters.txt
  // updates (the bundle is frozen in the APK) and (b) guarantee config drift.
  // The JS bundle therefore only does what native CANNOT: popup patching,
  // provider-API synthetic intercepts, anti-adblock-detector stripping, and
  // cosmetic DOM sweeping.
  const sharedScript = buildAllScriptsWithScriptlets(
    providerHost,
    providerId,
    [],
    apiIntercepts,
    // V6: skip the disable-devtool guard ONLY for providers whose Next.js
    // player loops on type=4 when the guard tampers with native methods.
    // peachify is reactSafe (guard deferred to post-hydration for #418), but
    // its guard is RE-ENABLED — it does not loop. zxcstream is the only one
    // that must skip the guard. Timing (doc-start vs post-hydration) is driven
    // separately by the `reactSafe` flag on the provider, NOT by skipGuard.
    skipGuard,
  );

  // Append per-provider cosmetic CSS
  const providerSnippet = generateProviderSnippet(providerConfig);
  if (!providerSnippet) return sharedScript;

  // Merge shared script with provider CSS into one IIFE
  return `(function(){
${sharedScript
  .replace(/^\s*\(function\s*\(\)\s*\{?/, "")
  .replace(/\}\s*\)\s*\(\s*\)\s*;?\s*true\s*;?\s*$/, "")
  .replace(/^\s*true\s*;?\s*$/, "")
  .trim()}

${providerSnippet}
})();
true;`;
}

/**
 * Q4 (expert perf consult follow-up 2026-08-18): minify the injected guard
 * bundle before it goes into the WebView. The ~50KB string from
 * makeConsolidatedScript carries readable indentation plus single-line and
 * block comments (our own scripts in @filmsnaps/shared + providerConfig.ts).
 * V8 still has to parse that whitespace/comment bloat at document_start, which
 * costs ~30–50ms of JS-compile time on low-end Android — pure latency on the
 * t2→t3 (provider-ready) gap with zero security benefit.
 *
 * IMPORTANT: a naive regex single-line-comment strip is UNSAFE here —
 * providerConfig.ts embeds single-quoted CSS selector strings containing
 * protocol URLs, and stripping from the double-slash would corrupt those URLs.
 * So this is a state-aware scanner: it preserves single/double/back-tick string
 * literals (including escaped chars) byte-for-byte and only strips comments in
 * CODE state. Horizontal whitespace is collapsed to one space; newlines are
 * preserved so automatic-semicolon-insertion can never be defeated. The
 * injected scripts are parenthesized IIFEs, so ASI is not relied upon across
 * newlines anyway. There are no regex literals in the bundle, so the scanner
 * never mis-classifies a regex as a comment.
 */
function minifyGuardScript(src: string): string {
  let out = "";
  const n = src.length;
  let i = 0;
  while (i < n) {
    const c = src[i];
    // line comment (code state only)
    if (c === "/" && src[i + 1] === "/") {
      i += 2;
      while (i < n && src[i] !== "\n") i++;
      continue;
    }
    // block comment (code state only) — collapse to a single space so
    // `a/*x*/b` never merges into `ab`.
    if (c === "/" && src[i + 1] === "*") {
      i += 2;
      while (i < n && !(src[i] === "*" && src[i + 1] === "/")) i++;
      i += 2; // skip closing */
      out += " ";
      continue;
    }
    // string / template literal — preserve verbatim, including escapes
    if (c === '"' || c === "'" || c === "`") {
      const quote = c;
      out += c;
      i++;
      while (i < n) {
        const ch = src[i];
        out += ch;
        if (ch === "\\") {
          if (i + 1 < n) {
            out += src[i + 1];
            i += 2;
            continue;
          }
          i++;
          break;
        }
        if (ch === quote) {
          i++;
          break;
        }
        i++;
      }
      continue;
    }
    // horizontal whitespace → single space (newlines preserved below)
    if (c === " " || c === "\t" || c === "\r") {
      out += " ";
      i++;
      while (i < n && (src[i] === " " || src[i] === "\t" || src[i] === "\r"))
        i++;
      continue;
    }
    if (c === "\n") {
      out += "\n";
      i++;
      continue;
    }
    out += c;
    i++;
  }
  return out;
}

/**
 * MEGAPLAY_410_MASK — document-side blind for the MegaPlay anime fallback chain.
 *
 * Two-layer 410 defense (expert verdict §7, megaplay-410-flash-expert-consultation.md):
 *
 *   PRIMARY  — `providerConfigs.megaplay.cssRules` in providerConfig.ts, injected at
 *              document_start via the shared doc-start bundle. A `<style>` rule is applied
 *              by the renderer's style engine AT PAINT, so `.error-content` is hidden and
 *              the dark `#070708` canvas shows from the first frame. It cannot over-blind the
 *              real player (the working document has no `.error-content`), and needs no removal.
 *
 *   SECONDARY — this JS overlay (backstop) + the 410-detection engine. Only matters if the
 *              CSS injection misses the first paint; it still polls innerText every 100ms
 *              (bypassing the 12s onLoadingFinish latency) and advances the chain.
 *
 * The WebView is a native window-overlay, so RN opacity can't reach it. Body stays visible
 * (opacity:1) so MegaPlay's autoplay runs. `window.__fs410MaskArmed` guards per-document;
 * handleLoadingStart re-arms on each chain-advance. OTA-shippable; no native code touched.
 */
const MEGAPLAY_410_MASK = `
(function(){
  if(window.__fs410MaskArmed) return;
  window.__fs410MaskArmed = true;

  var OVERLAY_ID = '__fs_410_overlay__';
  var maskRemoved = false;
  var fast410Timer = null;
  var videoCheckTimer = null;
  var errorTicks = 0;

  // 1. Overlay backstop (secondary). CSS rule in providerConfigs.megaplay is the
  //    primary paint-level hide; this only covers the 1-frame window if that misses.
  function createOverlay() {
    if (document.getElementById(OVERLAY_ID)) return;
    var overlay = document.createElement('div');
    overlay.id = OVERLAY_ID;
    overlay.style.cssText = 'position:fixed;top:0;left:0;width:100vw;height:100vh;z-index:2147483647;background:#070708;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;font-family:sans-serif;';
    overlay.innerHTML = '<style>@keyframes __fs_spin__{to{transform:rotate(360deg)}}</style>' +
                        '<div style="width:32px;height:32px;border:3px solid rgba(212,162,55,0.2);border-top-color:#D4A237;border-radius:50%;animation:__fs_spin__ .8s linear infinite"></div>' +
                        '<div style="color:#A1A1AA;font-size:13px;">Connecting to source\\u2026</div>';
    document.documentElement.appendChild(overlay);
  }
  createOverlay();

  function removeMask() {
    if (maskRemoved) return;
    maskRemoved = true;
    var o = document.getElementById(OVERLAY_ID);
    if (o) o.remove();
    if (fast410Timer) clearInterval(fast410Timer);
    if (videoCheckTimer) clearInterval(videoCheckTimer);
    // Safety net: nudge autoplay now that the page is visible (try/catch swallows
    // autoplay-policy rejections — body stays opacity:1 so the player's own
    // visibility-gated autoplay still runs).
    var vs = document.querySelectorAll('video');
    for (var i = 0; i < vs.length; i++) {
      try { if (vs[i].paused) vs[i].play().catch(function(){}); } catch (e) {}
    }
    if (window.ReactNativeWebView) {
      window.ReactNativeWebView.postMessage(JSON.stringify({ type: 'anime-playing' }));
    }
  }

  // 2. Fast 410 detection — polls innerText every 100ms from document_start, so the
  //    error text is caught the instant the HTML parses (bypasses the 12s onLoadingFinish
  //    + 2.5s settle delays → chain advances in ~300ms). errorTicks debounce (~3 ticks)
  //    avoids transient interstitial text firing a false 410.
  fast410Timer = setInterval(function() {
    if (!document.body) return;
    // textContent INCLUDES text inside display:none subtrees (unlike innerText),
    // so the PRIMARY CSS hide (providerConfigs.megaplay) does NOT blind detection.
    var errEl = document.querySelector('.error-content, .error-code, div[class*="error"]');
    var text = (errEl && errEl.textContent) ? errEl.textContent : (document.body.textContent || '');
    // 410 AND 404/not-found are RETRYABLE per id-space. MegaPlay returns a 404 for
    // a specific id-space (e.g. mal) when the title only lives in the other
    // (ani) — so a 404 must advance the chain, NOT terminate (verified by logs:
    // mal/21/1175 → 404, ani/21/1175 → plays). Only when all 4 space×audio combos
    // fail does RN exhaust and show "No sources available on MegaPlay".
    if (text.includes('Error Code: 410') || text.includes('404') || text.toLowerCase().includes('not found')) {
      errorTicks++;
      if (errorTicks >= 3) {
        clearInterval(fast410Timer);
        if (window.ReactNativeWebView) {
          window.ReactNativeWebView.postMessage(JSON.stringify({ type: 'anime-410' }));
        }
      }
    } else {
      errorTicks = 0;
    }
  }, 100);

  // 3. Relaxed video monitor — reveal on actively-playing video OR metadata loaded
  //    with real dimensions (JWPlayer keeps video paused / zero-dim during MSE buffering).
  videoCheckTimer = setInterval(function() {
    var videos = document.querySelectorAll('video');
    for (var i = 0; i < videos.length; i++) {
      var v = videos[i];
      if (v.error) continue;
      if (!v.paused && v.currentTime > 0.1) { removeMask(); return; }
      if (v.readyState >= 1 && v.videoWidth > 0 && v.videoHeight > 0) { removeMask(); return; }
    }
  }, 500);

  // 4. Safety timeout (15s) — if no video AND no 410 detected by now, the page is
  //    definitively dead/blank/hung. Do NOT removeMask() (that reveals the broken
  //    hidden page = black void). Instead post anime-410 so RN advances the chain;
  //    on the final combo RN triggers __fs410Exhaust → "No sources available"
  //    message (expert verdict §3). Clears fast410Timer so it cannot double-post
  //    after RN advances.
  setTimeout(function() {
    if (!maskRemoved) {
      clearInterval(fast410Timer);
      if (window.ReactNativeWebView) {
        window.ReactNativeWebView.postMessage(
          JSON.stringify({ type: 'anime-410', reason: 'timeout' }),
        );
      }
    }
  }, 15000);

  // 5. Hooks (RN-side).
  window.__fs410Reveal = function() { removeMask(); };
  window.__fs410Exhaust = function() {
    clearInterval(fast410Timer);
    clearInterval(videoCheckTimer);
    maskRemoved = true;
    // (Re)create the overlay if a prior removeMask() (e.g. a dead <video> with
    // bogus dimensions, or a 15s timeout race) already stripped it — otherwise the
    // terminal message would never render and the user sees a blank dark canvas.
    var el = document.getElementById(OVERLAY_ID);
    if (!el) {
      el = document.createElement('div');
      el.id = OVERLAY_ID;
      el.style.cssText = 'position:fixed;top:0;left:0;width:100vw;height:100vh;z-index:2147483647;background:#070708;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;font-family:sans-serif;';
      document.documentElement.appendChild(el);
    }
    el.innerHTML = '<div style="color:#D4A237;font-size:14px;text-align:center;padding:20px;">No sources available on MegaPlay</div>';
  };
})();
true;`;

/**
 * Self-contained terminal overlay for the MegaPlay 410/404 fallback chain. Unlike
 * `window.__fs410Exhaust` (which only exists if MEGAPLAY_410_MASK armed on the current
 * document), this script force-renders the "No sources available on MegaPlay" message
 * regardless of prior mask state — so the user always sees it on true exhaustion instead
 * of a blank dark canvas. RN injects this directly on chain exhaustion. JS-only / OTA.
 */
const MEGAPLAY_410_EXHAUST = `
(function(){
  try {
    var OVERLAY_ID = '__fs_410_overlay__';
    var el = document.getElementById(OVERLAY_ID);
    if (!el) {
      el = document.createElement('div');
      el.id = OVERLAY_ID;
      el.style.cssText = 'position:fixed;top:0;left:0;width:100vw;height:100vh;z-index:2147483647;background:#070708;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;font-family:sans-serif;';
      (document.head || document.documentElement).appendChild(el);
    }
    el.innerHTML = '<div style="color:#D4A237;font-size:14px;text-align:center;padding:20px;">No sources available on MegaPlay</div>';
    // Un-hide any error markup the PRIMARY CSS hid, so the user sees WHY (the 410/404).
    var errs = document.querySelectorAll('.error-content, .error-code, div[class*="error"]');
    for (var i = 0; i < errs.length; i++) {
      errs[i].style.setProperty('display', 'block', 'important');
      errs[i].style.setProperty('visibility', 'visible', 'important');
      errs[i].style.setProperty('opacity', '1', 'important');
    }
  } catch (e) {}
})();
true;`;

/**
 * Inject a floating "Next Episode" button into the WebView page.
 * On click, posts a next-episode message back to React Native.
 * Same style/position as skip buttons.
 */
function injectNextEpisodeBtn(
  webViewRef: React.RefObject<PlayerWebViewRef | null>,
) {
  webViewRef.current?.injectJavaScript(`
(function(){
  var btn = document.getElementById('__rn_next_ep_btn');
  if (btn) {
    btn.style.setProperty('display', 'flex', 'important');
    btn.style.setProperty('visibility', 'visible', 'important');
    btn.style.setProperty('opacity', '1', 'important');
    return;
  }
  if (!document.getElementById('__rn_next_ep_btn_css')) {
    var css = document.createElement('style');
    css.id = '__rn_next_ep_btn_css';
    css.textContent = '#__rn_next_ep_btn{position:fixed!important;right:24px!important;bottom:26%!important;z-index:2147483647!important;display:flex!important;align-items:center!important;background:rgba(14,14,17,0.92)!important;color:#D4A237!important;font-weight:600!important;font-size:13px!important;padding:10px 18px!important;border-radius:9999px!important;border:1px solid rgba(212,162,55,0.4)!important;cursor:pointer!important;box-shadow:0 6px 16px rgba(0,0,0,0.5)!important;backdrop-filter:blur(8px)!important;font-family:system-ui,-apple-system,sans-serif!important;gap:8px!important;visibility:visible!important;opacity:1!important;pointer-events:auto!important;line-height:1!important;}@media (orientation: landscape){#__rn_next_ep_btn{bottom:28%!important;right:32px!important;}}@media (max-height: 480px){#__rn_next_ep_btn{bottom:32%!important;}}';
    document.head.appendChild(css);
  }
  var b = document.createElement('div');
  b.id = '__rn_next_ep_btn';
  b.innerHTML = '<svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor"><path d="M6 18l8.5-6L6 6v12zM16 6v12h2V6h-2z"/></svg><span>Next Episode</span>';
  b.onclick = function() {
    if (window.ReactNativeWebView && window.ReactNativeWebView.postMessage) {
      window.ReactNativeWebView.postMessage(JSON.stringify({type: "next-episode"}));
    }
    b.remove();
  };
  if (!window.__rn_next_ep_fsWatch) {
    window.__rn_next_ep_fsWatch = true;
    document.addEventListener('fullscreenchange', function() {
      var el = document.getElementById('__rn_next_ep_btn');
      if (!el) return;
      var fsEl = document.fullscreenElement || document.webkitFullscreenElement;
      if (fsEl && !fsEl.contains(el)) {
        fsEl.appendChild(el);
      } else if (!fsEl && !document.body.contains(el)) {
        document.body.appendChild(el);
      }
    });
  }
  var targetEl = document.fullscreenElement || document.webkitFullscreenElement || document.body;
  targetEl.appendChild(b);
})();
true;
`);
}

/**
 * Remove the injected next episode button.
 */
function removeNextEpisodeBtn(
  webViewRef: React.RefObject<PlayerWebViewRef | null>,
) {
  webViewRef.current?.injectJavaScript(`
(function(){
  var el = document.getElementById('__rn_next_ep_btn');
  if (el) { el.style.transition = 'opacity 0.3s'; el.style.opacity = '0'; setTimeout(function(){el.remove();}, 300); }
})();
true;
`);
}

/**
 * Inject a floating skip button directly into the WebView page.
 * Attaches to the video's parent container so it survives fullscreen.
 * Also listens for fullscreenchange to re-parent if needed.
 */
function injectPageSkipBtn(
  webViewRef: React.RefObject<PlayerWebViewRef | null>,
  endSec: number,
  label: string,
) {
  webViewRef.current?.injectJavaScript(`
(function(){
  var btn = document.getElementById('__rn_skip_btn');
  if (btn) {
    btn.style.setProperty('display', 'flex', 'important');
    btn.style.setProperty('visibility', 'visible', 'important');
    btn.style.setProperty('opacity', '1', 'important');
    return;
  }

  // Inject a dedicated stylesheet so no page CSS overrides us
  if (!document.getElementById('__rn_skip_btn_css')) {
    var css = document.createElement('style');
    css.id = '__rn_skip_btn_css';
    css.textContent = '#__rn_skip_btn{position:fixed!important;right:24px!important;bottom:26%!important;z-index:2147483647!important;display:flex!important;align-items:center!important;background:rgba(14,14,17,0.92)!important;color:#D4A237!important;font-weight:600!important;font-size:13px!important;padding:10px 18px!important;border-radius:9999px!important;border:1px solid rgba(212,162,55,0.4)!important;cursor:pointer!important;box-shadow:0 6px 16px rgba(0,0,0,0.5)!important;backdrop-filter:blur(8px)!important;font-family:system-ui,-apple-system,sans-serif!important;gap:8px!important;visibility:visible!important;opacity:1!important;pointer-events:auto!important;line-height:1!important;}@media (orientation: landscape){#__rn_skip_btn{bottom:28%!important;right:32px!important;}}@media (max-height: 480px){#__rn_skip_btn{bottom:32%!important;}}';
    document.head.appendChild(css);
  }

  var b = document.createElement('div');
  b.id = '__rn_skip_btn';
  b.innerHTML = '<svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor"><path d="M6 18l8.5-6L6 6v12zM16 6v12h2V6h-2z"/></svg><span>' + '${label}' + '</span>';
  b.onclick = function() {
    var _t = ${endSec};
    var vids = document.querySelectorAll('video');
    for (var i = 0; i < vids.length; i++) { vids[i].currentTime = _t; }
    var frames = document.querySelectorAll('iframe');
    for (var fi = 0; fi < frames.length; fi++) {
      try { var fv = (frames[fi].contentDocument||frames[fi].contentWindow.document).querySelectorAll('video'); for (var vi = 0; vi < fv.length; vi++) { fv[vi].currentTime = _t; } } catch(e) {}
    }
    b.remove();
  };

  // Register fullscreenchange listener (once) to re-parent button into fullscreen element
  if (!window.__rn_skip_fsWatch) {
    window.__rn_skip_fsWatch = true;
    document.addEventListener('fullscreenchange', function() {
      var el = document.getElementById('__rn_skip_btn');
      if (!el) return;
      var fsEl = document.fullscreenElement || document.webkitFullscreenElement;
      if (fsEl && !fsEl.contains(el)) {
        fsEl.appendChild(el);
      } else if (!fsEl && !document.body.contains(el)) {
        document.body.appendChild(el);
      }
    });
  }

  // Attach to fullscreen element if already in fullscreen, otherwise body
  var targetEl = document.fullscreenElement || document.webkitFullscreenElement || document.body;
  targetEl.appendChild(b);
})();
true;
`);
}

/**
 * Remove the injected skip button from the WebView page.
 */
function removePageSkipBtn(
  webViewRef: React.RefObject<PlayerWebViewRef | null>,
) {
  webViewRef.current?.injectJavaScript(`
(function(){
  var el = document.getElementById('__rn_skip_btn');
  if (el) { el.style.transition = 'opacity 0.3s'; el.style.opacity = '0'; setTimeout(function(){el.remove();}, 300); }
})();
true;
`);
}

interface VideoWebViewProps {
  type: "movie" | "tv";
  id: string;
  season?: number;
  episode?: number;
  onClose?: () => void;
  initialProvider?: string;
  backdropUrl?: string;
  /** Anime session flag — enables MegaPlay + resolves ids. */
  isAnime?: boolean;
  animeMalId?: number;
  animeAnilistId?: number | null;
  animeAudio?: "sub" | "dub";
}

export function VideoWebView({
  type,
  id,
  season,
  episode,
  onClose,
  initialProvider,
  backdropUrl,
  isAnime,
  animeMalId,
  animeAnilistId,
  animeAudio = "sub",
}: VideoWebViewProps) {
  useKeepAwake();
  const insets = useSafeAreaInsets();
  const { settings, updateSetting } = useSettings();
  const { height: SCREEN_HEIGHT, width: SCREEN_WIDTH } =
    Dimensions.get("window");
  const webViewRef = useRef<PlayerWebViewRef>(null);
  // Ad-suppression spray (expert V4 §4A): timers for the onLoadingStart
  // re-injection retries. The bundle's boot guard makes re-injection
  // idempotent, so retries at +100/+300ms are safe no-ops if t=0 landed.
  const injectionTimersRef = useRef<ReturnType<typeof setTimeout>[]>([]);
  const providerHostRef = useRef<string>("");
  const navigationChainRef = useRef<Set<string>>(new Set());
  const pageLoadedRef = useRef(false);
  const navigationGenRef = useRef(0);
  const navigationAttemptsRef = useRef(0);
  const navigationReceivedRef = useRef(false);
  const progressRef = useRef<{
    currentTime: number;
    duration: number;
    percent: number;
  }>({ currentTime: 0, duration: 0, percent: 0 });
  const startAtRef = useRef<number>(0);
  const [startAtTime, setStartAtTime] = useState<number>(0);
  const lastSavePctRef = useRef<number>(0);

  // ── PlaybackEngine: single source of truth for progress + intro/next-episode
  // lifecycle (the watch-progress redesign). One engine per watch session;
  // every time source funnels into engine.ingest() and the UI derives from its
  // state. Initialized lazily so it exists before the first onMessage fires.
  const engineRef = useRef<PlaybackEngine | null>(null);
  if (!engineRef.current) {
    engineRef.current = new PlaybackEngine(
      buildEpisodeKey(type, id, season, episode),
      0,
    );
  }
  // Latest updateOverlays callback (stable subscription reads this ref so it
  // never closes over stale render-scope values).
  const updateOverlaysRef = useRef<
    ((s: ReturnType<PlaybackEngine["getState"]>) => void) | null
  >(null);
  // Mirror refs for values the mount-once subscription needs. Assigned to their
  // current values further down (after those values are declared).
  const introSegmentsRef = useRef<IntroDbResponse | null>(null);
  const providerRef = useRef<ProviderDefinition | undefined>(undefined);
  const seasonRef = useRef<number | undefined>(undefined);
  const episodeRef = useRef<number | undefined>(undefined);
  const typeRef = useRef(type);
  const idRef = useRef(id);
  // Next-episode arming bookkeeping — binds the button to episode identity so
  // it can never leak to the next episode (the reported "stuck button" bug).
  const armedEpisodeRef = useRef<string>("");
  const prevPctRef = useRef(0);
  const lastSaveAtRef = useRef(0);
  // type/id are stable props — mirror them immediately.
  typeRef.current = type;
  idRef.current = id;

  // ── Subscribe to the engine once (mount). The callback reads updateOverlaysRef
  // so it always invokes the latest closure (no stale render-scope values). ──
  useEffect(() => {
    if (!engineRef.current) return;
    const unsub = engineRef.current.subscribe((s) => {
      if (s.currentTime > 0 || s.duration > 0) {
        setLoadState((prev) =>
          prev.type !== "PLAYING" ? { type: "PLAYING" } : prev,
        );
      }
      updateOverlaysRef.current?.(s);
    });
    return unsub;
  }, []);

  // Ã¢â€â‚¬Ã¢â€â‚¬ Unified load state machine Ã¢â€â‚¬Ã¢â€â‚¬
  type LoadState =
    | { type: "LOADING"; enteredAt: number }
    | { type: "SLOW"; enteredAt: number }
    | { type: "PLAYING" }
    | { type: "FAILED"; reason: string; isCloudflare?: boolean };

  const [loadState, setLoadState] = useState<LoadState>({
    type: "LOADING",
    enteredAt: Date.now(),
  });

  const [resumeChipText, setResumeChipText] = useState<string | null>(null);

  // ── Q1 (expert perf consult 2026-08-17): load-at-t0 ──
  // The old `slideInReady` state withheld `source.uri` for a fixed 350 ms so
  // the player could "slide in" before the provider was contacted. That gated
  // the *network trigger* behind a *visual animation* — ~300 ms of pure dead
  // air before DNS/TLS/embed fetch even started. We now start loading at t=0
  // (the moment the route mounts) and let the existing LOADING state + blur
  // backdrop cover the load, exactly as before. The container-opacity fade the
  // expert suggested is intentionally NOT done here: this player's WebView is a
  // window-overlay attached to android.R.id.content (bypassing Fabric), so its
  // visibility is driven natively by the anchor, not by an RN opacity — an RN
  // fade would not hide it and could flash. The latency win is achieved by
  // starting the load immediately; the visual during load is unchanged.
  const watchMountMs = useRef<number>(Date.now()).current;

  // ── LOADING → SLOW transition (10s) ──
  const slowTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const loadingGenRef = useRef(0);
  useEffect(() => {
    if (loadState.type === "LOADING") {
      const gen = ++loadingGenRef.current;
      slowTimerRef.current = setTimeout(() => {
        if (gen === loadingGenRef.current) {
          setLoadState((prev) => {
            if (prev.type === "LOADING")
              return { type: "SLOW", enteredAt: Date.now() };
            return prev;
          });
        }
      }, 10000);
    }
    return () => {
      if (slowTimerRef.current) clearTimeout(slowTimerRef.current);
    };
  }, [loadState.type]);

  // ── SLOW → FAILED transition (30s total without recovery) ──
  const slowFailGenRef = useRef(0);
  const slowFailTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => {
    if (loadState.type === "SLOW") {
      const gen = ++slowFailGenRef.current;
      // 20s more after SLOW entered (10s LOADING + 20s SLOW = 30s total)
      slowFailTimerRef.current = setTimeout(() => {
        if (gen === slowFailGenRef.current) {
          setLoadState((prev) => {
            if (prev.type === "SLOW")
              return { type: "FAILED", reason: "Timed out." };
            return prev;
          });
        }
      }, 20000);
    }
    return () => {
      if (slowFailTimerRef.current) clearTimeout(slowFailTimerRef.current);
    };
  }, [loadState.type]);
  const [showPicker, setShowPicker] = useState(false);
  const [auditMode, setAuditMode] = useState(false);
  const [auditHosts, setAuditHosts] = useState<string[]>([]);

  // â”€â”€ Skip Intro/Recap state â”€â”€
  const [introSegments, setIntroSegments] = useState<IntroDbResponse | null>(
    null,
  );
  introSegmentsRef.current = introSegments;
  const skipBtnInjectedRef = useRef(false);

  // â”€â”€ Next Episode button state (injected as floating button in WebView at 95%) â”€â”€
  const [nextEpInfo, setNextEpInfo] = useState<{
    season: number;
    episode: number;
  } | null>(null);
  const nextEpBtnInjectedRef = useRef(false);
  const nextEpFetchingRef = useRef(false);

  // Tracks the PROVIDER's own in-page fullscreen (driven by its native button
  // via the `cf:fullscreen` message). This is independent of RN `isFullscreen`
  // (which is only toggled by our overlay control). Used to restore fullscreen
  // after "Next Episode" remounts the WebView (see goToNextEpisode + load
  // handlers below).
  const providerFsRef = useRef(false);
  // Set the moment "Next Episode" is tapped while the provider is fullscreen,
  // so the new episode's page can be re-expanded once it loads.
  const wasFullscreenOnNextRef = useRef(false);

  // Per-title session type wins over the global Hard Mode Split: a regular
  // movie tapped in anime mode must NOT get anime-only servers (megaplay is
  // keyed by MAL ids and can't play a TMDB movie), and an anime title tapped
  // in movie_tv mode MUST still get anime-capable servers. The `isAnime` route
  // param carries the per-title decision made by the detail page.
  const providers = useMemo(() => {
    if (isAnime) {
      return filterAnimeProviders(getEnabledProviders());
    }
    return getNonAnimeProviders();
  }, [isAnime]);

  // Initial provider: explicit route param wins; otherwise fall back to the
  // user's "Default Source" setting if it's still an enabled provider, else the
  // first available provider.
  const initialProviderId = useMemo(() => {
    if (initialProvider && providers.some((p) => p.id === initialProvider)) {
      return initialProvider;
    }
    if (
      settings.defaultServer &&
      providers.some((p) => p.id === settings.defaultServer)
    ) {
      return settings.defaultServer;
    }
    return providers[0]?.id ?? "";
  }, [initialProvider, providers, settings.defaultServer]);

  const [providerId, setProviderId] = useState<string>(initialProviderId);

  // ── MegaPlay sub/dub preference (persisted, per-title) ──
  // MegaPlay's embed honors opts.audio (/stream/<space>/<id>/<ep>/<sub|dub>).
  // We remember the last choice per TMDB id so re-opening the same anime keeps
  // it. Defaults to the prop (usually "sub").
  const [audio, setAudio] = useState<"sub" | "dub">(animeAudio ?? "sub");
  const audioPrefKey = useMemo(
    () => (id != null ? `megaplay:audio:${id}` : null),
    [id],
  );
  useEffect(() => {
    if (!audioPrefKey) return;
    let alive = true;
    AsyncStorage.getItem(audioPrefKey)
      .then((v) => {
        if (alive && (v === "sub" || v === "dub")) setAudio(v);
      })
      .catch(() => {});
    return () => {
      alive = false;
    };
  }, [audioPrefKey]);
  const changeAudio = useCallback(
    (next: "sub" | "dub") => {
      setAudio(next);
      if (audioPrefKey)
        AsyncStorage.setItem(audioPrefKey, next).catch(() => {});
    },
    [audioPrefKey],
  );

  const [isFullscreen, setIsFullscreen] = useState(false);

  // Ã¢â€â‚¬Ã¢â€â‚¬ Overlay auto-hide (only in fullscreen) Ã¢â€â‚¬Ã¢â€â‚¬
  const overlayOpacity = useRef(new Animated.Value(1)).current;
  const hideTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [overlayVisible, setOverlayVisible] = useState(true);

  const scheduleHide = useCallback(() => {
    if (hideTimerRef.current) clearTimeout(hideTimerRef.current);
    hideTimerRef.current = setTimeout(() => {
      Animated.timing(overlayOpacity, {
        toValue: 0,
        duration: 300,
        useNativeDriver: true,
      }).start(() => setOverlayVisible(false));
    }, 4000);
  }, [overlayOpacity]);

  // Toggle fullscreen orientation
  useEffect(() => {
    if (isFullscreen) {
      ScreenOrientation.lockAsync(
        ScreenOrientation.OrientationLock.LANDSCAPE,
      ).catch(() => {});
      scheduleHide();
    } else {
      ScreenOrientation.lockAsync(
        ScreenOrientation.OrientationLock.PORTRAIT_UP,
      ).catch(() => {});
      if (hideTimerRef.current) clearTimeout(hideTimerRef.current);
      setOverlayVisible(true);
      Animated.timing(overlayOpacity, {
        toValue: 1,
        duration: 200,
        useNativeDriver: true,
      }).start();
    }
    return () => {
      if (hideTimerRef.current) clearTimeout(hideTimerRef.current);
    };
  }, [isFullscreen, scheduleHide, overlayOpacity]);

  // Ã¢â€â‚¬Ã¢â€â‚¬ Pause detection — keep controls visible while paused Ã¢â€â‚¬Ã¢â€â‚¬
  const pausedRef = useRef(false);
  const pauseCheckIntervalRef = useRef<ReturnType<typeof setInterval> | null>(
    null,
  );

  useEffect(() => {
    if (!isFullscreen) {
      if (pauseCheckIntervalRef.current) {
        clearInterval(pauseCheckIntervalRef.current);
        pauseCheckIntervalRef.current = null;
      }
      return;
    }

    let lastTime = progressRef.current.currentTime;
    pauseCheckIntervalRef.current = setInterval(() => {
      const ct = progressRef.current.currentTime;
      if (ct === lastTime && ct > 0) {
        pausedRef.current = true;
        if (hideTimerRef.current) clearTimeout(hideTimerRef.current);
        setOverlayVisible(true);
        overlayOpacity.setValue(1);
      } else if (ct !== lastTime && ct > 0) {
        pausedRef.current = false;
      }
      lastTime = ct;
    }, 2000);

    return () => {
      if (pauseCheckIntervalRef.current) {
        clearInterval(pauseCheckIntervalRef.current);
        pauseCheckIntervalRef.current = null;
      }
      pausedRef.current = false;
    };
  }, [isFullscreen, overlayOpacity]);

  const showOverlay = useCallback(() => {
    setOverlayVisible(true);
    Animated.timing(overlayOpacity, {
      toValue: 1,
      duration: 200,
      useNativeDriver: true,
    }).start();
    scheduleHide();
  }, [overlayOpacity, scheduleHide]);

  const orientationRestoredRef = useRef(false);
  const restorePortrait = useCallback(() => {
    if (orientationRestoredRef.current) return;
    orientationRestoredRef.current = true;
    ScreenOrientation.lockAsync(
      ScreenOrientation.OrientationLock.PORTRAIT_UP,
    ).catch(() => {});
  }, []);
  useEffect(() => {
    return () => {
      if (!orientationRestoredRef.current) {
        ScreenOrientation.lockAsync(
          ScreenOrientation.OrientationLock.PORTRAIT_UP,
        ).catch(() => {});
      }
    };
  }, []);

  const [showEpPicker, setShowEpPicker] = useState(false);
  const [currentSeason, setCurrentSeason] = useState<number>(season ?? 1);
  const [currentEpisode, setCurrentEpisode] = useState<number>(episode ?? 1);
  seasonRef.current = currentSeason;
  episodeRef.current = currentEpisode;

  // ── Anime fallback chain (desktop parity, verdict §9 Q5) ──
  // 2D state machine (FS-410 fix, consultation §8): exhausts (id-space × audio)
  // per (title, episode). Previously a single global `chainSpace` leaked across
  // episodes — once flipped to "ani" it never reset, so later episodes started on
  // "ani" and the chain declared exhausted without ever trying "mal".
  type ChainSpace = "mal" | "ani";
  type ChainAudio = "sub" | "dub";
  type ChainCombo = `${ChainSpace}:${ChainAudio}`;

  // Preferred audio drives the queue order: a Dub fan tolerates a missing MAL
  // episode if AniList has the Dub, but NOT being forced to Sub on MAL.
  const preferredAudio: ChainAudio = audio; // current state is the user's choice
  const altAudio: ChainAudio = preferredAudio === "sub" ? "dub" : "sub";
  const FALLBACK_QUEUE = useMemo<
    Array<{ space: ChainSpace; audio: ChainAudio }>
  >(
    () => [
      { space: "mal", audio: preferredAudio },
      { space: "ani", audio: preferredAudio },
      { space: "mal", audio: altAudio },
      { space: "ani", audio: altAudio },
    ],
    [preferredAudio, altAudio],
  );

  const [chainSpace, setChainSpace] = useState<ChainSpace>("mal");
  // Single source of truth for which combos we've tried this episode. A Set is
  // O(1) and resets instantly on episode change (below) — no state-machine lib.
  const triedCombos = useRef<Set<ChainCombo>>(new Set());

  // Per-(title, episode) scope: clear tried combos + reset to MAL on change.
  // We intentionally DO NOT reset `audio` here — if the user prefers Dub, the next
  // episode should also start on Dub.
  useEffect(() => {
    triedCombos.current.clear();
    setChainSpace("mal");
  }, [id, currentEpisode, currentSeason]);

  // MegaPlay is keyed by MAL-relative episodes, not TMDB's. Translate the
  // current TMDB (season, episode) through the twin map's cour offset so the
  // right cour plays (verdict Q7 — never guess; fall back to raw TMDB ep only
  // when the mapper has no entry for this title). Independent of chainSpace
  // (the episode number is identical in both MAL/AniList id spaces).
  const animeEpisode = useMemo(() => {
    if (!isAnime || type !== "tv" || id == null) return undefined;
    const r = resolveShow(id, currentSeason, currentEpisode);
    return r.ok ? r.episode : currentEpisode;
  }, [isAnime, type, id, currentSeason, currentEpisode]);

  const animeResolved = useMemo(() => {
    if (!isAnime || animeMalId == null) return null;
    // The AniList id may arrive via the route param (aid) OR be derived from MAL
    // via the map's m2a table when the deep-link omitted it. Without this, a 410
    // chain with no threaded aid has nowhere to fall back to (see FS-410 logs).
    const aniFromParam = animeAnilistId;
    const aniDerived =
      aniFromParam == null ? malToAni(animeMalId) : aniFromParam;
    const useAni = chainSpace === "ani";
    const resolvedId = useAni ? aniDerived : animeMalId;
    if (resolvedId == null) return null;
    return {
      idSpace: useAni ? ("ani" as const) : ("mal" as const),
      id: resolvedId,
      // MAL-relative episode for MegaPlay; TMDB ep for non-anime providers.
      episode: animeEpisode ?? currentEpisode,
    };
  }, [
    isAnime,
    animeMalId,
    animeAnilistId,
    chainSpace,
    animeEpisode,
    currentEpisode,
  ]);

  const episodeKey = useMemo(
    () => buildEpisodeKey(type, id, currentSeason, currentEpisode),
    [type, id, currentSeason, currentEpisode],
  );

  // ── Auto-resume on OPEN (mount only) ──
  // When the show first opens, land the user on the most-relevant episode
  // (the one getResumePoint picks — last watched / next after a completed one).
  // This runs ONCE per mount and must NOT re-run on in-player episode changes,
  // otherwise an explicit "I want ep 3" click would be overridden back to the
  // most-recently-watched episode. The actual per-episode seek is applied by
  // the second effect below.
  const didAutoResumeRef = useRef(false);
  useEffect(() => {
    if (didAutoResumeRef.current) return;
    didAutoResumeRef.current = true;
    (async () => {
      try {
        const resume =
          type === "tv"
            ? await getResumePoint(
                id,
                "tv",
                currentSeason,
                currentEpisode,
                isAnime,
              )
            : await getProgress(id, "movie", undefined, undefined, isAnime);
        if (
          resume &&
          resume.season != null &&
          resume.episode != null &&
          type === "tv" &&
          !resume.completed &&
          (resume.season !== currentSeason || resume.episode !== currentEpisode)
        ) {
          // Only switch episodes on open — never during in-player navigation.
          setCurrentSeason(resume.season);
          setCurrentEpisode(resume.episode);
        }
      } catch (e) {
        console.warn("[WatchHistory] Auto-resume check error:", e);
      }
    })();
  }, []);

  // ── Seed the engine for the CURRENTLY SELECTED episode ──
  // Runs on every episode / provider change so switching servers or episodes
  // re-applies the right resume position. It reads ONLY the selected episode's
  // own progress (getProgress — no fallback to other episodes), so an explicit
  // episode switch always plays that episode (from its own resume, if any, else
  // from 0). engine.setEpisode also opens a 10 s settle window for
  // resume:'none' providers so an unpredictable self-resume can't fight us.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const resume =
          type === "tv"
            ? await getProgress(
                id,
                "tv",
                currentSeason,
                currentEpisode,
                isAnime,
              )
            : await getProgress(id, "movie", undefined, undefined, isAnime);
        if (cancelled) return;
        let resumeSeconds = 0;
        // resume:'none' providers (e.g. screenscape) manage their OWN resume;
        // seeding startAt would double-seek and fight them. We still load the
        // engine resume point below so progress tracking + the backward-clamp
        // settle window work, but we don't drive the native seek for them.
        const canSeedSeek =
          currentProvider && getResumeMode(currentProvider) !== "none";
        if (
          resume &&
          resume.currentTime > 5 &&
          !resume.completed &&
          canSeedSeek
        ) {
          resumeSeconds = resume.currentTime;
          startAtRef.current = resumeSeconds;
          setStartAtTime(resumeSeconds);
          const mins = Math.floor(resumeSeconds / 60);
          const secs = Math.floor(resumeSeconds % 60);
          setResumeChipText(
            `Resuming from ${mins}:${secs.toString().padStart(2, "0")}`,
          );
          setTimeout(() => setResumeChipText(null), 3000);
        } else {
          // No applicable resume for THIS episode — start from 0 so we never
          // carry a stale startAt into the embed URL / native seek of a
          // different episode (that was the "switched to ep 3 but still resumed
          // ep 2" bug).
          resumeSeconds = 0;
          startAtRef.current = 0;
          setStartAtTime(0);
        }
        // (Re)create the engine state for this episode with the resume point.
        engineRef.current?.setEpisode(episodeKey, resumeSeconds);
      } catch (e) {
        console.warn("[WatchHistory] Resume seed error:", e);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [episodeKey, providerId]);

  const currentProvider = providers.find((p) => p.id === providerId);
  providerRef.current = currentProvider;
  const onMegaplay = currentProvider?.animeOnly === true;

  // V6: peachify (#418) fix — reactSafe providers (Next.js) must NOT receive the
  // heavy guard bundle at document_start (it breaks React 18 hydration). The
  // bundle is instead deferred to injectedJavaScriptAfterLoad (post-hydration)
  // and NO disable-devtool neutralization runs at doc-start (native side). The
  // post-hydration bundle keeps ad-block scriptlets but skips the guard.
  const reactSafe = currentProvider?.reactSafe === true;

  // Source 5 / zxcstream disable-devtool `type=4` loop — expert consultation
  // (2026-08-15): the loop is the FuncToString detector in zxcstream's inlined
  // `theajack/disable-devtool` lib, falsely tripped by the Android WebView native
  // console-serialization bridge. The fix is the surgical `console.log` mask
  // (DEVTOOL_CONSOLE_MASK_SCRIPT) injected at document_start, which defeats the
  // detector without touching `Function.prototype.toString` (React hydration is
  // safe). With the mask in place, full RN injection is re-enabled for zxcstream.
  // `disableInjection` remains as a one-line fallback: if the loop ever returns,
  // set `disableInjection: true` on the provider to force both props empty.
  const suppressInjection = currentProvider?.disableInjection === true;
  const devtoolPatchScript =
    !suppressInjection && currentProvider?.disableDevtoolPatch === true
      ? DEVTOOL_CONSOLE_MASK_SCRIPT
      : "";

  // Q5 (expert perf consult 2026-08-17): memoize the guard bundle.
  // `makeConsolidatedScript` builds a ~50KB string (buildAllScriptsWithScriptlets
  // + provider snippet). Previously it was rebuilt on EVERY render — including
  // every progress tick and overlay toggle — burning JS-thread CPU during the
  // exact window we want to be fast (and risking frame drops during the slide-in).
  // It only depends on the selected provider + its injection flags, plus the
  // OTA config version (defensive invalidation — see note below), so we memoize
  // it per provider switch. The injected JS bundle is compiled into the app
  // (from @filmsnaps/shared + providerConfig.ts); today the OTA config
  // (providers.json/filters.txt) feeds the *native* engine, not this bundle — so
  // `configVersion` is a zero-cost defensive hook that guarantees correctness if
  // a future feature starts injecting OTA-driven rules into the bundle.
  //
  // Q4 (expert follow-up 2026-08-18): the memo output is minified via
  // minifyGuardScript() to shave V8's document_start parse time.
  const [configVersion, setConfigVersion] = useState(0);
  useEffect(() => {
    let alive = true;
    getConfigVersion()
      .then((v) => {
        if (alive) setConfigVersion(v);
      })
      .catch(() => {});
    return () => {
      alive = false;
    };
  }, []);
  const injectedScriptValue = useMemo(() => {
    if (!currentProvider?.baseUrl) return "";
    const raw = makeConsolidatedScript(
      new URL(currentProvider.baseUrl).hostname,
      currentProvider.id,
      // V6 (2026-08-15): zxcstream no longer needs to skip the guard. The
      // `disableDevtoolPatch` console.log mask defeats the FuncToString
      // (type=4) detector at document_start, so the full guard + scriptlets
      // bundle can run (post-hydration, via reactSafe). Re-enabling the guard
      // restores the ad-blocking protection that was previously disabled to
      // stop the loop. All providers now run the guard unless a provider
      // explicitly opts out via its own flag.
      false,
    );
    return minifyGuardScript(raw);
  }, [providerId, reactSafe, suppressInjection, configVersion]);
  console.log(
    `[VideoWebView] script length (memoized+minified): ${injectedScriptValue.length}, provider: ${currentProvider?.id ?? "null"}, reactSafe: ${reactSafe}, disableInjection: ${suppressInjection}, devtoolPatch: ${devtoolPatchScript.length > 0}, configVersion: ${configVersion}`,
  );

  // App media hook for `progress: 'app'` providers (nxsha / zxcstream /
  // cinemaos / videasy / etc.) — reads the page's own <video> at ~1 Hz and
  // posts `fs:progress`. Injected into the SAME timing slot as the guard
  // bundle so it survives the provider's own lifecycle. Native providers don't
  // emit nothing, so they don't need it (and we avoid a redundant 1 Hz poll).
  const mediaHookScript =
    !suppressInjection &&
    currentProvider &&
    getProgressMode(currentProvider) === "app"
      ? MEDIA_HOOK_SCRIPT
      : "";

  // The guard bundle + media hook share one timing slot. reactSafe providers
  // get it at document_start suppressed and instead receive it post-hydration.
  const docStartScript = reactSafe ? "" : injectedScriptValue + mediaHookScript;
  const afterLoadScript = reactSafe
    ? injectedScriptValue + mediaHookScript
    : "";

  // Ad-suppression spray (expert V4 §4A): re-inject the full bundle at page
  // start via the proven main-thread `injectJavaScript` ref, then retry at
  // +100ms and +300ms. `onPageStarted` may fire before the new document
  // commits (t=0 can land in the old renderer); the retries land in the
  // committed document before screenscape's deferred first /api/ads/cycles
  // poll. The bundle's Symbol.for('__filmsnaps_preload_guard') boot guard
  // makes any post-first injection a no-op.
  const handleLoadingStart = useCallback(() => {
    // Q6 (expert perf consult): RN-side waterfall marker. Native t0/t1/t2 are
    // logged in PlayerWebViewOverlayView; this gives t0-from-mount on the JS
    // side so the two log streams can be correlated in logcat.
    console.log(
      `[WATERFALL] RN: onLoadingStart at ${Date.now() - watchMountMs}ms from watch-mount`,
    );
    navigationReceivedRef.current = true;
    // Clear pending retries from a previous load/navigation.
    injectionTimersRef.current.forEach(clearTimeout);
    injectionTimersRef.current = [];

    if (!docStartScript) return;
    // V6: reactSafe providers get the bundle post-hydration via
    // injectedJavaScriptAfterLoad — suppress the doc-start spray (it would
    // re-inject at document_start and break Next.js hydration #418).
    if (reactSafe) return;

    webViewRef.current?.injectJavaScript(docStartScript);
    const t1 = setTimeout(() => {
      webViewRef.current?.injectJavaScript(docStartScript);
    }, 100);
    const t2 = setTimeout(() => {
      webViewRef.current?.injectJavaScript(docStartScript);
    }, 300);
    injectionTimersRef.current = [t1, t2];

    // MegaPlay 410 blind (§10 Q13/Q14): RN's injectedJavaScriptBeforeContentLoaded
    // runs once per WebView instance, NOT per in-document navigation. The 410 chain
    // advances via the `source` prop (same WebView, new document), so on each
    // advance the mask must be re-injected or the raw 410 page flashes. Re-arm it on
    // every onLoadingStart (mirrors the guard spray above). The mask's boot guard
    // (an id check) makes a re-injection a no-op if it already ran in this document.
    if (onMegaplay) {
      webViewRef.current?.injectJavaScript(MEGAPLAY_410_MASK);
      const m1 = setTimeout(() => {
        webViewRef.current?.injectJavaScript(MEGAPLAY_410_MASK);
      }, 100);
      const m2 = setTimeout(() => {
        webViewRef.current?.injectJavaScript(MEGAPLAY_410_MASK);
      }, 300);
      injectionTimersRef.current.push(m1, m2);
    }
  }, [docStartScript, onMegaplay]);

  const isTV = type === "tv";

  // Ã¢â€â‚¬Ã¢â€â‚¬ Preconnect to top providers when picker opens Ã¢â€â‚¬Ã¢â€â‚¬
  useEffect(() => {
    if (!showPicker || !currentProvider) return;
    // Warm up DNS/TLS for the next 2-3 providers by injecting link rel=preconnect
    const currentIndex = providers.findIndex((p) => p.id === providerId);
    const candidates = providers
      .filter((_, i) => i !== currentIndex)
      .slice(0, 3);
    candidates.forEach((p) => {
      try {
        const origin = new URL(p.baseUrl).origin;
        webViewRef.current?.injectJavaScript(`
          (function() {
            var link = document.createElement('link');
            link.rel = 'preconnect';
            link.href = '${origin}';
            document.head.appendChild(link);
          })();
          true;
        `);
      } catch (e) {}
    });
  }, [showPicker, providerId, providers, currentProvider]);

  useEffect(() => {
    if (currentProvider) {
      try {
        providerHostRef.current = new URL(currentProvider.baseUrl).hostname;
      } catch (e) {
        providerHostRef.current = "";
      }
    }
  }, [currentProvider]);

  useEffect(() => {
    navigationReceivedRef.current = false;
    const gen = navigationGenRef.current;
    // If no navigation received within 30s, transition to FAILED
    const noNavTimer = setTimeout(() => {
      if (!navigationReceivedRef.current) {
        setLoadState({ type: "FAILED", reason: "No response from source." });
      }
    }, 30000);
    const safetyTimer = setTimeout(() => {
      setLoadState((prev) => {
        if (prev.type === "LOADING" || prev.type === "SLOW")
          return { type: "FAILED", reason: "Timed out." };
        return prev;
      });
    }, 35000);
    return () => {
      clearTimeout(noNavTimer);
      clearTimeout(safetyTimer);
    };
  }, [providerId, currentSeason, currentEpisode]);

  const watchUrl = useMemo(() => {
    if (!currentProvider) return "";
    const startAt = startAtTime > 0 ? startAtTime : undefined;
    const isAnimeProvider = isAnime && currentProvider.animeOnly;
    // MegaPlay is MAL/AniList-keyed with a MAL-relative episode; other anime
    // providers (nxsha) are TMDB-keyed, so they take the raw TMDB id/episode.
    const embedId = isAnimeProvider
      ? (animeResolved?.id?.toString() ?? id)
      : id;
    const embedEpisode =
      isAnimeProvider && animeResolved ? animeResolved.episode : currentEpisode;
    const opts =
      isAnimeProvider && animeResolved
        ? { idSpace: animeResolved.idSpace, audio }
        : undefined;
    const embedPath =
      type === "tv" && currentSeason && currentEpisode
        ? currentProvider.embed.tv(
            embedId,
            currentSeason,
            embedEpisode,
            startAt,
            opts,
          )
        : currentProvider.embed.movie(embedId, startAt, opts);
    const url = `${currentProvider.baseUrl}${embedPath}`;
    if (__DEV__)
      console.log(
        `[FS-410] watchUrl chainSpace=${chainSpace} isAnimeProvider=${isAnimeProvider} embedId=${embedId} idSpace=${opts?.idSpace ?? "n/a"} url=${url}`,
      );
    return url;
  }, [
    currentProvider,
    isAnime,
    type,
    id,
    currentSeason,
    currentEpisode,
    startAtTime,
    animeResolved,
    audio,
  ]);

  const seekTo = useCallback((time: number) => {
    webViewRef.current?.injectJavaScript(`
      (function() {
        var _t = ${Math.floor(time)};

        // Search current document
        var vids = document.querySelectorAll('video');
        for (var i = 0; i < vids.length; i++) { vids[i].currentTime = _t; }

        // Search child iframes
        if (vids.length === 0) {
          var frames = document.querySelectorAll('iframe');
          for (var fi = 0; fi < frames.length; fi++) {
            try {
              var fvids = (frames[fi].contentDocument || frames[fi].contentWindow.document).querySelectorAll('video');
              for (var vi = 0; vi < fvids.length; vi++) { fvids[vi].currentTime = _t; }
            } catch(e) {}
          }
        }

        // Try window.__seekTo bridge as fallback
        if (typeof window.__seekTo !== 'undefined') { window.__seekTo(_t); }
      })();
      true;
    `);
  }, []);

  // â”€â”€ Fetch intro/recap/outro segments when TV episode loads â”€â”€
  useEffect(() => {
    // Per-provider toggle from the registry (skipIntroEnabled). Absent flag
    // = enabled, so the button still shows for every provider until one opts
    // out in packages/shared/src/providers/registry.ts.
    const skipIntro = currentProvider
      ? isSkipIntroEnabled(currentProvider)
      : false;
    if (type !== "tv" || !currentSeason || !currentEpisode || !skipIntro) {
      setIntroSegments(null);
      return;
    }

    // Clear immediately so old segments don't persist into new episode
    setIntroSegments(null);
    skipBtnInjectedRef.current = false;

    let cancelled = false;

    (async () => {
      try {
        // Step 1: Get IMDB ID from TMDB
        const externalIds = await tmdbApi.getExternalIds(id, "tv");
        const imdbId: string | undefined = externalIds?.imdb_id;
        if (!imdbId) {
          console.log("[IntroDetect] No IMDB ID for TMDB id=" + id);
          return;
        }

        // Step 2: Fetch intro segments from introdb.app
        const segments = await fetchIntroSegments(
          imdbId,
          currentSeason,
          currentEpisode,
        );
        if (!cancelled) {
          setIntroSegments(segments);
          if (segments?.intro) {
            console.log(
              "[IntroDetect] Found intro: " +
                segments.intro.start_sec +
                "s â€“ " +
                segments.intro.end_sec +
                "s (conf=" +
                segments.intro.confidence +
                ")",
            );
          }
          if (segments?.recap) {
            console.log(
              "[IntroDetect] Found recap: " +
                segments.recap.start_sec +
                "s â€“ " +
                segments.recap.end_sec +
                "s",
            );
          }
        }
      } catch (e: any) {
        console.warn(
          "[IntroDetect] Fetch failed: " + (e?.message ?? String(e)),
        );
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [type, id, currentSeason, currentEpisode, currentProvider]);

  // ── Skip-Intro button: now event-driven from the PlaybackEngine (see
  // updateOverlaysFromEngine). The old 500 ms poll was removed — the engine
  // emits on every 1 Hz media-hook sample / native progress message, which is
  // exactly the right cadence and cannot leak state across episodes.

  const handleClose = useCallback(() => {
    restorePortrait();
    const prog = progressRef.current;

    if (prog.currentTime > 5) {
      saveProgress({
        tmdbId: id,
        mediaType: type,
        isAnime,
        providerId,
        currentTime: prog.currentTime,
        duration: prog.duration,
        percent: prog.percent,
        season: isTV ? currentSeason : undefined,
        episode: isTV ? currentEpisode : undefined,
        updatedAt: Date.now(),
        completed: prog.percent >= 0.95,
      }).catch(() => {});
    }
    setTimeout(() => onClose?.(), 200);
  }, [
    restorePortrait,
    onClose,
    id,
    type,
    providerId,
    isTV,
    currentSeason,
    currentEpisode,
  ]);

  // Ã¢â€â‚¬Ã¢â€â‚¬ Periodic force-save (every 10s) Ã¢â€â‚¬Ã¢â€â‚¬
  useEffect(() => {
    const intervalId = setInterval(() => {
      const prog = progressRef.current;

      if (prog.currentTime > 5) {
        saveProgress({
          tmdbId: id,
          mediaType: type,
          isAnime,
          providerId,
          currentTime: prog.currentTime,
          duration: prog.duration,
          percent: prog.percent,
          season: isTV ? currentSeason : undefined,
          episode: isTV ? currentEpisode : undefined,
          updatedAt: Date.now(),
          completed: prog.percent >= 0.95,
        }).catch(() => {});
      }
    }, 10000);
    return () => clearInterval(intervalId);
  }, [id, type, providerId, isTV, currentSeason, currentEpisode]);

  // Ã¢â€â‚¬Ã¢â€â‚¬ Save progress on app background (user switches apps, receives call) Ã¢â€â‚¬Ã¢â€â‚¬
  useEffect(() => {
    const sub = AppState.addEventListener("change", (state) => {
      if (state === "background" || state === "inactive") {
        const prog = progressRef.current;
        if (prog.currentTime > 5) {
          saveProgress({
            tmdbId: id,
            mediaType: type,
            isAnime,
            providerId,
            currentTime: prog.currentTime,
            duration: prog.duration,
            percent: prog.percent,
            season: isTV ? currentSeason : undefined,
            episode: isTV ? currentEpisode : undefined,
            updatedAt: Date.now(),
            completed: prog.percent >= 0.95,
          }).catch(() => {});
        }
      }
    });
    return () => sub.remove();
  }, [id, type, isAnime, providerId, isTV, currentSeason, currentEpisode]);

  // Ã¢â€â‚¬Ã¢â€â‚¬ Save progress on unmount Ã¢â€â‚¬Ã¢â€â‚¬
  const unmountSavedRef = useRef(false);
  useEffect(() => {
    return () => {
      // Clear any pending ad-suppression spray timers.
      injectionTimersRef.current.forEach(clearTimeout);
      injectionTimersRef.current = [];

      if (unmountSavedRef.current) return;
      unmountSavedRef.current = true;
      const prog = progressRef.current;

      if (prog.currentTime > 5) {
        saveProgress({
          tmdbId: id,
          mediaType: type,
          isAnime,
          providerId,
          currentTime: prog.currentTime,
          duration: prog.duration,
          percent: prog.percent,
          season: isTV ? currentSeason : undefined,
          episode: isTV ? currentEpisode : undefined,
          updatedAt: Date.now(),
          completed: prog.percent >= 0.95,
        }).catch((err: unknown) => console.warn("Unmount save failed", err));
      }
    };
  }, [id, type, isAnime, providerId, isTV, currentSeason, currentEpisode]);

  // ── Next-Episode button: now event-driven from the PlaybackEngine (see
  // updateOverlaysFromEngine). The old 2 s poll is removed — the engine only
  // arms the button when the playhead genuinely advanced forward to >= 95% this
  // session, and binds the button to the episode key so it can never stay stuck
  // on the next episode.

  // â”€â”€ Switch to next episode when user taps the floating button â”€â”€
  const goToNextEpisode = useCallback(() => {
    if (!nextEpInfo) return;
    // Tear down the next-episode affordance immediately so it can't appear to
    // "stay" while the new episode loads. The engine is re-seeded for the new
    // episode by the seed effect (episodeKey change), which resets
    // maxForwardPercent — so the button cannot re-arm until the new episode is
    // genuinely watched to the end again.
    if (nextEpBtnInjectedRef.current) {
      removeNextEpisodeBtn(webViewRef);
      nextEpBtnInjectedRef.current = false;
    }
    armedEpisodeRef.current = "";
    nextEpFetchingRef.current = false;
    setNextEpInfo(null);
    // Remember whether the provider was fullscreen so the new episode's page
    // can be re-expanded after the WebView remount (provider fullscreen is lost
    // on remount and can't be re-entered without a fresh user gesture).
    wasFullscreenOnNextRef.current = providerFsRef.current;
    setCurrentSeason(nextEpInfo.season);
    setCurrentEpisode(nextEpInfo.episode);
    setMountGen((g) => g + 1);
    setLoadState({ type: "LOADING", enteredAt: Date.now() });
  }, [nextEpInfo]);

  const switchInFlightRef = useRef(false);

  const switchProvider = async (newId: string) => {
    if (switchInFlightRef.current) return;
    switchInFlightRef.current = true;
    setLoadState({ type: "LOADING", enteredAt: Date.now() });
    setShowPicker(false);
    navigationChainRef.current = new Set();
    pageLoadedRef.current = false;
    navigationGenRef.current += 1;
    navigationAttemptsRef.current = 0;
    const latestTime = (progressRef.current as any).currentTime ?? 0;
    if (latestTime > 5) {
      startAtRef.current = latestTime;
      setStartAtTime(latestTime);
    }

    // clearAllState is no longer needed â€” native destroys old WebView.
    // Keeping it as belt-and-suspenders for global CookieManager state.
    try {
      await clearAllState();
    } catch {
      // State clearing is best-effort; proceed anyway
    }
    setProviderId(newId);
    // mountGen bump REMOVED â€” native handles switch via double-buffering
    // watchUrl recomputes â†’ sourceUri setter â†’ native switchProvider()

    // Debounce gate: re-allow trigger after 2s
    setTimeout(() => {
      switchInFlightRef.current = false;
    }, 2000);
  };

  const [mountGen, setMountGen] = useState(0);
  const webViewKey = `player-${mountGen}`;

  const getProviderDisplayName = (p: ProviderDefinition): string =>
    p.displayName || p.name || p.id;

  const retry = () => {
    if (loadState.type === "FAILED") {
      setLoadState({ type: "LOADING", enteredAt: Date.now() });
    }
    navigationAttemptsRef.current = 0;
    setMountGen((g) => g + 1);
  };

  const tryNextProvider = useCallback(() => {
    if (providers.length <= 1) return;
    const currentIndex = providers.findIndex((p) => p.id === providerId);
    const nextIndex = (currentIndex + 1) % providers.length;
    const nextP = providers[nextIndex];
    if (nextP && nextP.id !== providerId) {
      switchProvider(nextP.id);
    }
  }, [providers, providerId]);

  // Ã¢â€â‚¬Ã¢â€â‚¬ Empty URL guard Ã¢â€â‚¬Ã¢â€â‚¬
  if (!watchUrl) {
    return (
      <View className="flex-1 items-center justify-center bg-black px-8">
        <View className="w-16 h-16 rounded-full bg-zinc-800 items-center justify-center mb-5">
          <Ionicons name="server" size={28} color={colors.textTertiary} />
        </View>
        <Text className="text-zinc-300 text-lg font-semibold mb-2">
          No player available
        </Text>
        <Text className="text-zinc-500 text-sm mb-8 text-center leading-5">
          No streaming sources are available. Try selecting a different source.
        </Text>
        <TouchableOpacity
          onPress={() => setShowPicker(true)}
          className="bg-primary rounded-xl py-3 px-6 flex-row items-center"
          activeOpacity={0.8}
        >
          <Ionicons name="server" size={16} color={colors.voidBlack} />
          <Text className="text-black font-bold text-sm ml-2">
            Choose Source
          </Text>
        </TouchableOpacity>
        <ServerPickerSheet
          visible={showPicker}
          providers={providers}
          currentId={providerId}
          onSelect={switchProvider}
          onClose={() => setShowPicker(false)}
          getDisplayName={getProviderDisplayName}
        />
      </View>
    );
  }

  // Ã¢â€â‚¬Ã¢â€â‚¬ Resume chip helper Ã¢â€â‚¬Ã¢â€â‚¬
  // ── updateOverlaysFromEngine ─────────────────────────────────────
  // Single place that turns PlaybackEngine state into (a) throttled storage
  // saves, (b) the Skip-Intro page button, and (c) the Next-Episode page
  // button. Called on every engine emit. This REPLACES the old 500 ms intro
  // poll and 2 s next-episode poll — both were timer-driven and leaked state
  // across episodes. Now everything is event-driven and episode-bound.
  function updateOverlaysFromEngine(
    state: ReturnType<PlaybackEngine["getState"]>,
  ): void {
    // (1) Mirror into progressRef so the unchanged stall/pause watchers keep working.
    progressRef.current = {
      currentTime: state.currentTime,
      duration: state.duration,
      percent: state.percent,
    };

    const provider = providerRef.current;
    const isTV = typeRef.current === "tv";
    const id = idRef.current;

    // (2) Throttled save (replaces the per-message applyProgress save path).
    const now = Date.now();
    const pctDiff = state.percent - lastSavePctRef.current;
    const threshold = state.percent > 0.9 ? 0.02 : 0.05;
    if (
      state.currentTime > 5 &&
      (pctDiff >= threshold || state.percent >= 0.95) &&
      now - lastSaveAtRef.current > 3000
    ) {
      lastSavePctRef.current = state.percent;
      lastSaveAtRef.current = now;
      saveProgress({
        tmdbId: id,
        mediaType: typeRef.current,
        isAnime,
        providerId: provider?.id,
        currentTime: state.currentTime,
        duration: state.duration,
        percent: state.percent,
        season: isTV ? seasonRef.current : undefined,
        episode: isTV ? episodeRef.current : undefined,
        updatedAt: now,
        completed: state.percent >= 0.95,
      }).catch(() => {});
    }
    if (isTV && prevPctRef.current < 0.95 && state.percent >= 0.95) {
      markCompleted(
        id,
        "tv",
        seasonRef.current,
        episodeRef.current,
        isAnime,
      ).catch(() => {});
    }
    prevPctRef.current = state.percent;

    // (3) Skip-Intro button — event-driven from engine.currentTime.
    if (
      isTV &&
      introSegmentsRef.current &&
      provider &&
      isUiEnabled(provider, "intro")
    ) {
      const active = getActiveSkipSegment(
        introSegmentsRef.current,
        state.currentTime,
      );
      if (active && !skipBtnInjectedRef.current) {
        injectPageSkipBtn(webViewRef, active.segment.end_sec, active.label);
        skipBtnInjectedRef.current = true;
      } else if (!active && skipBtnInjectedRef.current) {
        removePageSkipBtn(webViewRef);
        skipBtnInjectedRef.current = false;
      }
    } else if (skipBtnInjectedRef.current) {
      removePageSkipBtn(webViewRef);
      skipBtnInjectedRef.current = false;
    }

    // (4) Next-Episode button — episode-bound state machine (the "stuck button" fix).
    // The button only arms when the playhead genuinely advanced forward to >= 95%
    // this session (engine.canArmNextEpisode), never when a resume/seek landed us
    // there. On any episode change the engine resets maxForwardPercent, so the
    // button cannot re-arm until the new episode is watched to the end again.
    if (isTV && provider && isUiEnabled(provider, "nextEpisode")) {
      if (state.episodeKey !== armedEpisodeRef.current) {
        // Episode changed → tear down any armed/visible button for the old one.
        if (nextEpBtnInjectedRef.current) {
          removeNextEpisodeBtn(webViewRef);
          nextEpBtnInjectedRef.current = false;
        }
        armedEpisodeRef.current = state.episodeKey;
        nextEpFetchingRef.current = false;
        setNextEpInfo(null);
      }
      if (
        engineRef.current?.canArmNextEpisode() &&
        !nextEpFetchingRef.current
      ) {
        nextEpFetchingRef.current = true;
        const s = seasonRef.current;
        const e = episodeRef.current;
        getNextEpisode(id, s ?? 1, e ?? 1)
          .then(({ nextSeason, nextEpisode, hasNext }) => {
            // Changed again while we were fetching — abort.
            if (state.episodeKey !== armedEpisodeRef.current) return;
            if (!hasNext) {
              // Final episode of the final season — no Next Episode button.
              setNextEpInfo(null);
              nextEpFetchingRef.current = false;
              return;
            }
            setNextEpInfo({ season: nextSeason, episode: nextEpisode });
            if (
              (nextSeason !== s || nextEpisode !== e) &&
              !nextEpBtnInjectedRef.current
            ) {
              injectNextEpisodeBtn(webViewRef);
              nextEpBtnInjectedRef.current = true;
            }
          })
          .catch(() => {
            nextEpFetchingRef.current = false;
          });
      }
    } else if (nextEpBtnInjectedRef.current) {
      removeNextEpisodeBtn(webViewRef);
      nextEpBtnInjectedRef.current = false;
    }
  }
  // Keep the mount-once subscription pointed at the latest closure.
  updateOverlaysRef.current = updateOverlaysFromEngine;

  const isLoadingState =
    loadState.type === "LOADING" || loadState.type === "SLOW";
  const isErrorState = loadState.type === "FAILED";

  return (
    <View className="flex-1 bg-black">
      {/* ── Controls overlay ── */}
      <PlayerControlOverlay
        isFullscreen={isFullscreen}
        isTV={isTV}
        loadState={loadState}
        resumeChipText={resumeChipText}
        overlayVisible={overlayVisible}
        showOverlay={showOverlay}
        overlayOpacity={overlayOpacity}
        onClose={handleClose}
        onToggleFullscreen={() => setIsFullscreen((f) => !f)}
        onServerPickerOpen={() => setShowPicker(true)}
        onEpisodePickerOpen={() => {
          setShowEpPicker(true);
        }}
        onTryNextSource={tryNextProvider}
        currentSeason={currentSeason}
        currentEpisode={currentEpisode}
        providerDisplayName={
          currentProvider ? getProviderDisplayName(currentProvider) : "Source"
        }
        providerId={providerId}
        auditMode={auditMode}
        onMegaplay={onMegaplay}
        audio={audio}
        onAudioChange={changeAudio}
      />

      {/* Server picker modal */}
      <ServerPickerSheet
        visible={showPicker}
        providers={providers}
        currentId={providerId}
        onSelect={switchProvider}
        onClose={() => setShowPicker(false)}
        getDisplayName={getProviderDisplayName}
      />

      {/* ── Episode picker modal (TV only) ── */}
      {isTV && (
        <EpisodeRail
          visible={showEpPicker}
          tvId={id}
          currentSeason={currentSeason}
          currentEpisode={currentEpisode}
          onSelect={(s, e) => {
            setCurrentSeason(s);
            setCurrentEpisode(e);
            setShowEpPicker(false);
            if (s !== currentSeason || e !== currentEpisode) {
              setMountGen((g) => g + 1);
              setLoadState({ type: "LOADING", enteredAt: Date.now() });
            }
          }}
          onClose={() => setShowEpPicker(false)}
        />
      )}

      {/* ── Audit Results Modal ── */}
      <Modal
        visible={auditHosts.length > 0 && !auditMode}
        transparent
        animationType="fade"
        onRequestClose={() => setAuditHosts([])}
      >
        <View className="flex-1 bg-black/70 items-center justify-center px-6">
          <View
            className="rounded-2xl w-full max-h-[60%] p-5 border"
            style={{
              backgroundColor: colors.bgCard,
              borderColor: colors.borderSubtle,
            }}
          >
            <View className="flex-row items-center justify-between mb-4">
              <View className="flex-row items-center gap-2">
                <Ionicons name="radio-outline" size={18} color={colors.gold} />
                <Text
                  className="text-base font-bold"
                  style={{
                    color: colors.textPrimary,
                    fontFamily: "Inter_600SemiBold",
                  }}
                >
                  Discovered Domains
                </Text>
              </View>
              <TouchableOpacity
                onPress={() => setAuditHosts([])}
                activeOpacity={0.7}
                accessibilityLabel="Close audit results"
                accessibilityRole="button"
                className="w-7 h-7 rounded-full items-center justify-center border"
                style={{
                  backgroundColor: colors.bgSurface,
                  borderColor: colors.borderSubtle,
                }}
              >
                <Ionicons name="close" size={16} color={colors.textSecondary} />
              </TouchableOpacity>
            </View>
            <Text
              className="text-xs mb-3"
              style={{ color: colors.textSecondary }}
            >
              {auditHosts.length} unique hosts captured during this session.
            </Text>
            <ScrollView className="flex-1" showsVerticalScrollIndicator={false}>
              {auditHosts.map((host) => (
                <View
                  key={host}
                  className="flex-row items-center py-2 px-3 rounded-lg mb-1.5 border"
                  style={{
                    backgroundColor: colors.bgSurface,
                    borderColor: colors.borderSubtle,
                  }}
                >
                  <Text
                    className="text-xs font-mono flex-1"
                    style={{ color: colors.textSecondary }}
                  >
                    {host}
                  </Text>
                </View>
              ))}
            </ScrollView>
            <TouchableOpacity
              onPress={() => {
                console.warn(
                  `[Audit] JSON:\n${JSON.stringify(auditHosts, null, 2)}`,
                );
                setAuditHosts([]);
              }}
              className="rounded-xl py-3 mt-4 items-center"
              style={{ backgroundColor: colors.gold }}
              activeOpacity={0.8}
            >
              <Text
                className="font-bold text-sm"
                style={{ color: colors.bg, fontFamily: "Inter_600SemiBold" }}
              >
                Export & Close
              </Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>

      {/* ── Player area ── */}
      <View
        style={
          !isFullscreen
            ? {
                height:
                  providerId === "nxsha"
                    ? SCREEN_HEIGHT * 0.4
                    : SCREEN_HEIGHT * 0.68,
                justifyContent: "center",
                marginTop: insets.top + 40,
              }
            : { flex: 1 }
        }
      >
        {backdropUrl && isLoadingState && (
          <ProgressiveImage
            uri={getImageUrl(backdropUrl, "w780")}
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              right: 0,
              bottom: 0,
            }}
            resizeMode="cover"
            blurRadius={Platform.OS === "android" ? 10 : 20}
          />
        )}
        {/* FAILED state inline overlay — keeps blurred backdrop visible */}
        {isErrorState && (
          <View
            className="absolute inset-0 z-30 items-center justify-center px-8"
            style={{ backgroundColor: "rgba(7, 7, 8, 0.90)" }}
          >
            <View
              className="w-16 h-16 rounded-2xl items-center justify-center mb-5 border"
              style={{
                backgroundColor: "rgba(239, 68, 68, 0.12)",
                borderColor: "rgba(239, 68, 68, 0.3)",
              }}
            >
              <Ionicons name="alert-circle" size={32} color={colors.error} />
            </View>
            <Text
              className="text-lg font-semibold mb-2 text-center"
              style={{
                color: colors.textPrimary,
                fontFamily: "Inter_600SemiBold",
              }}
            >
              {loadState.isCloudflare
                ? "Source Verifying You"
                : "Source Unavailable"}
            </Text>
            <Text
              className="text-sm mb-6 text-center leading-6 max-w-xs"
              style={{ color: colors.textSecondary }}
            >
              {loadState.reason}
            </Text>
            <View
              className="flex-row gap-2.5"
              style={{ flexWrap: "wrap", justifyContent: "center" }}
            >
              {providers.length > 1 && (
                <TouchableOpacity
                  onPress={tryNextProvider}
                  className="rounded-xl py-3 px-5 flex-row items-center shadow-md"
                  style={{ backgroundColor: colors.gold }}
                  activeOpacity={0.8}
                >
                  <Ionicons name="play-forward" size={15} color={colors.bg} />
                  <Text
                    className="font-bold text-xs ml-2"
                    style={{
                      color: colors.bg,
                      fontFamily: "Inter_600SemiBold",
                    }}
                  >
                    Try Next Source
                  </Text>
                </TouchableOpacity>
              )}
              <TouchableOpacity
                onPress={retry}
                className="rounded-xl py-3 px-5 flex-row items-center border"
                style={{
                  backgroundColor: colors.bgCard,
                  borderColor: colors.borderSubtle,
                }}
                activeOpacity={0.8}
              >
                <Ionicons name="refresh" size={15} color={colors.textPrimary} />
                <Text
                  className="font-bold text-xs ml-2"
                  style={{
                    color: colors.textPrimary,
                    fontFamily: "Inter_600SemiBold",
                  }}
                >
                  Retry
                </Text>
              </TouchableOpacity>
              <TouchableOpacity
                onPress={() => setShowPicker(true)}
                className="rounded-xl py-3 px-5 flex-row items-center border"
                style={{
                  backgroundColor: colors.bgCard,
                  borderColor: colors.borderSubtle,
                }}
                activeOpacity={0.8}
              >
                <Ionicons
                  name="server-outline"
                  size={15}
                  color={colors.textSecondary}
                />
                <Text
                  className="font-bold text-xs ml-2"
                  style={{
                    color: colors.textSecondary,
                    fontFamily: "Inter_600SemiBold",
                  }}
                >
                  All Sources
                </Text>
              </TouchableOpacity>
              <TouchableOpacity
                onPress={handleClose}
                className="rounded-xl py-3 px-5 flex-row items-center border"
                style={{
                  backgroundColor: colors.bgSurface,
                  borderColor: colors.borderSubtle,
                }}
                activeOpacity={0.8}
              >
                <Text
                  className="font-bold text-xs"
                  style={{
                    color: colors.textSecondary,
                    fontFamily: "Inter_500Medium",
                  }}
                >
                  Back to details
                </Text>
              </TouchableOpacity>
            </View>
            {/* "Report this source" link */}
            <TouchableOpacity
              onPress={() => {
                try {
                  const { reportBrokenSource } = require("../lib/reportSource");
                  reportBrokenSource(providerId, id, type, loadState.reason);
                } catch {}
              }}
              className="mt-6"
              activeOpacity={0.7}
            >
              <Text className="text-zinc-600 text-xs underline">
                Report this source
              </Text>
            </TouchableOpacity>
          </View>
        )}
        <View
          style={
            !isFullscreen
              ? {
                  width: "100%",
                  height: "100%",
                  backgroundColor: colors.playerBg,
                }
              : { flex: 1 }
          }
        >
          <PlayerWebView
            key={webViewKey}
            ref={webViewRef}
            source={{ uri: watchUrl }}
            style={{
              width: "100%",
              height: "100%",
              backgroundColor: colors.playerBg,
            }}
            allowsFullscreenVideo={true}
            injectedJavaScriptBeforeContentLoaded={
              suppressInjection
                ? ""
                : (devtoolPatchScript ? devtoolPatchScript + "\n" : "") +
                  docStartScript +
                  // MegaPlay 410 blind: document-side mask (§10 Q13/Q14). Runs at
                  // document_start so the raw 410 page never paints a visible frame.
                  // RN opacity can't reach the native window-overlay WebView.
                  (onMegaplay ? "\n" + MEGAPLAY_410_MASK : "")
            }
            injectedJavaScriptAfterLoad={
              suppressInjection ? "" : afterLoadScript
            }
            referrer={currentProvider?.baseUrl || ""}
            setSupportMultipleWindows={false}
            javaScriptCanOpenWindowsAutomatically={false}
            auditMode={auditMode}
            onAuditData={(event) => {
              const { hosts: hostsStr } = event.nativeEvent;
              const domains = hostsStr
                ? hostsStr.split(",").filter(Boolean)
                : [];
              setAuditHosts(domains);
            }}
            userAgent="Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.165 Mobile Safari/537.36"
            onLoadingStart={handleLoadingStart}
            onLoadingFinish={(event) => {
              console.log(
                `[WATERFALL] RN: onLoadingFinish at ${Date.now() - watchMountMs}ms from watch-mount`,
              );
              setLoadState((prev) =>
                prev.type === "LOADING" || prev.type === "SLOW"
                  ? { type: "PLAYING" }
                  : prev,
              );
              const gen = navigationGenRef.current;
              setTimeout(() => {
                if (
                  navigationGenRef.current === gen &&
                  !pageLoadedRef.current
                ) {
                  pageLoadedRef.current = true;
                }
              }, 15000);
              const seekTime = startAtRef.current;
              if (seekTime > 5) {
                seekTo(seekTime);
                startAtRef.current = 0;
              }
              // Restore fullscreen after a "Next Episode" remount. The provider's
              // own fullscreen is native (onShowCustomView) and is destroyed when
              // the WebView remounts, but the device stays landscape because the
              // prior cf:fullscreen lock was never released. The provider's button
              // can't be re-pressed without a fresh gesture, so expand OUR layout
              // to fill the screen — the freshly-loaded WebView then shows full-size.
              if (wasFullscreenOnNextRef.current) {
                wasFullscreenOnNextRef.current = false;
                console.log(
                  `[FS-RESTORE] RN: expanding RN fullscreen after next-episode remount`,
                );
                webViewRef.current?.injectJavaScript(
                  "console.log('[FS-RESTORE] expanding RN layout to fullscreen; providerFsWas=" +
                    (providerFsRef.current ? "true" : "false") +
                    "'); true;",
                );
                setIsFullscreen(true);
              }
              // MegaPlay 410 detection now lives inside MEGAPLAY_410_MASK (fast 200ms
              // innerText poll posts anime-410 from document_start) — no separate probe.
              // The mask is injected via injectedJavaScriptBeforeContentLoaded + re-armed
              // on every onLoadingStart, so injecting ANIME_410_PROBE here is redundant and
              // would double-post anime-410 on doc 1 (skipping the working source).
            }}
            onHttpError={(syntheticEvent) => {
              const err = syntheticEvent.nativeEvent;
              if (err.statusCode === 403) {
                const isCloudflare = !!providerId;
                setLoadState({
                  type: "FAILED",
                  reason: isCloudflare
                    ? "Behind Cloudflare protection. Try a different source."
                    : "Access denied.",
                  isCloudflare,
                });
              } else {
                setLoadState({
                  type: "FAILED",
                  reason: `HTTP ${err.statusCode}: ${err.description || ""}`,
                });
              }
            }}
            onEscapeBlocked={() => {
              setLoadState({
                type: "FAILED",
                reason:
                  "This source redirected away from the player. Try switching sources.",
              });
            }}
            onRenderProcessGone={() => {
              setLoadState({ type: "LOADING", enteredAt: Date.now() });
              setMountGen((g) => g + 1);
            }}
            onMessage={(event) => {
              try {
                const data = JSON.parse(event.nativeEvent.data);
                if (data.type === "__diag" || data.type === "player:diag") {
                  return;
                }
                if (data.type === "cf:content-ready") {
                  console.log(
                    `[WATERFALL] RN: t3 cf:content-ready at ${Date.now() - watchMountMs}ms from watch-mount`,
                  );
                  setLoadState({ type: "PLAYING" });
                  navigationReceivedRef.current = true;
                  pageLoadedRef.current = true;
                  const seekTime = startAtRef.current;
                  if (seekTime > 5) {
                    seekTo(seekTime);
                    startAtRef.current = 0;
                  }
                  // Restore fullscreen after a "Next Episode" remount.
                  if (wasFullscreenOnNextRef.current) {
                    wasFullscreenOnNextRef.current = false;
                    console.log(
                      `[FS-RESTORE] RN: expanding RN fullscreen after next-episode remount (content-ready)`,
                    );
                    setIsFullscreen(true);
                  }
                  return;
                }
                if (data.type === "cf:fullscreen") {
                  providerFsRef.current = !!data.entering;
                  // Keep OUR layout in sync with the provider's native fullscreen
                  // (onShowCustomView / onHideCustomView). Without this, after a
                  // next-episode remount we force RN fullscreen, but tapping the
                  // provider's button to exit only rotates to portrait — leaving
                  // our layout stuck full. Enter -> RN full, exit -> RN collapse.
                  setIsFullscreen(!!data.entering);
                  if (data.entering) {
                    ScreenOrientation.lockAsync(
                      ScreenOrientation.OrientationLock.LANDSCAPE,
                    ).catch(() => {});
                    setOverlayVisible(false);
                    overlayOpacity.setValue(0);
                  } else {
                    ScreenOrientation.lockAsync(
                      ScreenOrientation.OrientationLock.PORTRAIT_UP,
                    ).catch(() => {});
                    setOverlayVisible(true);
                    Animated.timing(overlayOpacity, {
                      toValue: 1,
                      duration: 200,
                      useNativeDriver: true,
                    }).start();
                  }
                  return;
                }
                if (data.type === "console") {
                  const level = data.level || "log";
                  const args = data.args || [];
                  const text = args.join(" ");
                  // Log ALL console levels from the page so user can see
                  // [ProgressTracker], [Bridge], and other diagnostic output
                  if (level === "error") {
                    console.warn(`[Page:ERR] ${text}`);
                  } else if (level === "warn") {
                    console.warn(`[Page:WARN] ${text}`);
                  } else {
                    console.log(`[Page:LOG] ${text}`);
                  }
                  return;
                }
                if (data.type === "next-episode") {
                  goToNextEpisode();
                  return;
                }
                // MegaPlay "Error Code: 410" fallback chain (desktop parity,
                // verdict §9 Q5): swap MAL↔AniList id space; exhaust when both tried.
                if (data.type === "anime-410") {
                  console.log(
                    `[FS-410] received anime-410 — chainSpace=${chainSpace} audio=${audio} tried=${Array.from(triedCombos.current).join(",")}`,
                  );
                  // Mark the combo we just loaded as tried.
                  const currentCombo: ChainCombo = `${chainSpace}:${audio}`;
                  triedCombos.current.add(currentCombo);

                  // Find the next untried combo in the preferred-audio-first queue.
                  const nextCombo = FALLBACK_QUEUE.find(
                    (c) => !triedCombos.current.has(`${c.space}:${c.audio}`),
                  );

                  if (!nextCombo) {
                    // Exhausted: all 4 (space × audio) combos failed. Surface the
                    // terminal error UI instead of silently staying on a dead page.
                    console.warn(
                      `[FS-410] fallback chain EXHAUSTED for id=${id} ep=${currentEpisode} (tried=${Array.from(triedCombos.current).join(",")})`,
                    );
                    setLoadState({
                      type: "FAILED",
                      reason:
                        "This episode isn't available on MegaPlay (tried sub & dub). Try another source.",
                    });
                    // RN's FAILED overlay sits behind the native window-overlay
                    // WebView and can't cover it, so render a self-contained
                    // in-document overlay (force-rendered regardless of whether the
                    // 410 mask armed on this document — that's why a bare
                    // window.__fs410Exhaust() could silently no-op and leave blank).
                    webViewRef.current?.injectJavaScript(MEGAPLAY_410_EXHAUST);
                    return;
                  }

                  // Apply the next combo. Navigation happens automatically because
                  // watchUrl depends on chainSpace + audio; the probe re-injects on
                  // the next onLoadingFinish. No remount, no forced reload (see
                  // consultation §7 — reload-in-place re-fetches the dead 410 doc).
                  setChainSpace(nextCombo.space);
                  if (nextCombo.audio !== audio) {
                    // changeAudio updates state AND persists to AsyncStorage, so the
                    // UI toggle reflects the working audio.
                    changeAudio(nextCombo.audio);
                  }
                  console.log(
                    `[FS-410] advancing -> space=${nextCombo.space} audio=${nextCombo.audio} (watchUrl follows via source prop): ${watchUrl}`,
                  );
                  return;
                }
                // Definitive "all clear": the 410 probe polled twice post-settle and
                // found NO 410/404/not-found text. Force-reveal the in-document mask
                // immediately — this is the source of truth and bypasses in-page video
                // heuristics (JWPlayer keeps the video paused / zero-dimensions during
                // MSE buffering, so the relaxed shouldUnmask() alone can lag). The mask
                // exposes a real playing source underneath the blind.
                // The in-document 410 mask confirmed an actively-playing <video> and
                // removed itself (removeMask posts anime-playing). Flip RN to PLAYING
                // so the LOADING/SLOW UI clears; the live video is already rendering
                // behind the now-removed mask. (The old anime-410-clear probe signal
                // is gone — the mask self-reveals before the chain even needs it.)
                if (data.type === "anime-playing") {
                  if (onMegaplay) {
                    console.log(
                      `[FS-410] received anime-playing — video confirmed, clearing load state`,
                    );
                    setLoadState({ type: "PLAYING" });
                    navigationReceivedRef.current = true;
                    pageLoadedRef.current = true;
                    const seekTime = startAtRef.current;
                    if (seekTime > 5) {
                      seekTo(seekTime);
                      startAtRef.current = 0;
                    }
                  }
                  return;
                }
                // All native progress sources funnel into the single
                // PlaybackEngine ingest path. The engine computes percent,
                // enforces monotonic forward progress, drives the settle window,
                // and (via its subscription) throttles saves + markCompleted +
                // the intro / next-episode affordances. We never trust the
                // provider's own percent — only its raw currentTime/duration.
                const ingestProgress = (
                  currentTime: number,
                  duration: number,
                ) => {
                  if (currentTime > 0 || duration > 0) {
                    setLoadState((prev) =>
                      prev.type !== "PLAYING" ? { type: "PLAYING" } : prev,
                    );
                  }
                  engineRef.current?.ingest(currentTime, duration);
                };

                // App media-hook (progress: 'app' providers) — reads the
                // cross-origin <video> at ~1 Hz and posts here.
                if (data.type === "fs:progress") {
                  const { currentTime = 0, duration = 0 } = data.data ?? {};
                  ingestProgress(currentTime, duration);
                  return;
                }

                if (
                  data.type === "player:progress" ||
                  data.type === "screenscape:progress"
                ) {
                  const { currentTime = 0, duration = 0 } = data.data ?? {};
                  ingestProgress(currentTime, duration);
                  return;
                }

                // VidZee live player events — { event, currentTime, duration }.
                if (data.type === "PLAYER_EVENT") {
                  const { currentTime = 0, duration = 0 } = data.data ?? {};
                  if (duration > 0) ingestProgress(currentTime, duration);
                  return;
                }

                // VidZee / viduki resume store — keyed by tmdb id. Seed resume
                // for the current title only until live progress has started
                // (then the native events take over).
                if (data.type === "MEDIA_DATA") {
                  const current = data.data?.[String(id)];
                  if (
                    current?.progress?.duration &&
                    engineRef.current?.getState().percent === 0
                  ) {
                    ingestProgress(
                      current.progress.watched ?? 0,
                      current.progress.duration,
                    );
                  }
                  return;
                }
              } catch (e) {}
            }}
          />
        </View>
      </View>

      {/* Per-server usage notes (hidden in fullscreen) */}
      {!isFullscreen && settings.showServerNotes && (
        <ServerNotes
          providerId={providerId}
          show={!isFullscreen}
          onDismiss={() => updateSetting("showServerNotes", false)}
        />
      )}
    </View>
  );
}
