import React, { useRef, useState, useCallback, useMemo, useEffect } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  ActivityIndicator,
  Dimensions,
  Animated,
  Image,
  Platform,
  Modal,
  ScrollView,
} from 'react-native';
import PlayerWebView, { PlayerWebViewRef } from '../modules/player-webview';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { getEnabledProviders, getImageUrl, buildAllScriptsWithScriptlets } from '@filmsnaps/shared';
import type { ProviderDefinition } from '@filmsnaps/shared';
import * as ScreenOrientation from 'expo-screen-orientation';
import { useKeepAwake } from 'expo-keep-awake';
import { saveProgress, getResumePoint, getProgress, markCompleted } from '../lib/watchHistory';
import { clearAllState } from '../modules/player-webview';
import { providerConfigs, generateProviderSnippet } from './providerConfig';
import { PlayerControlOverlay } from './player/PlayerControlOverlay';
import { EpisodeRail } from './player/EpisodeRail';
import { ServerPickerSheet } from './player/ServerPickerSheet';

// ── Guard scripts ── injected via shared package ──
// Generated by buildAllScriptsWithScriptlets() from @filmsnaps/shared:
//   - 15-layer popup/ad-blocking guard (buildGuardScript)
//   - uBlock Origin anti-anti-adblock scriptlets
//   - Content-ready detection + progress bridge
//   - Provider-specific cosmetic CSS (from providerConfig.ts)

function makeConsolidatedScript(providerHost: string, providerId?: string): string {
  // Start with shared guard + uBO scriptlets
  const sharedScript = buildAllScriptsWithScriptlets(providerHost, providerId);

  // Append per-provider cosmetic CSS
  const providerSnippet = providerId
    ? generateProviderSnippet(providerConfigs[providerId])
    : '';
  if (!providerSnippet) return sharedScript;

  // Merge shared script with provider CSS into one IIFE
  return `(function(){
${
    sharedScript
      .replace(/^\s*\(function\s*\(\)\s*\{?/, '')
      .replace(/\}\s*\)\s*\(\s*\)\s*;?\s*true\s*;?\s*$/, '')
      .replace(/^\s*true\s*;?\s*$/, '')
      .trim()
}

${providerSnippet}
})();
true;`;
}

interface VideoWebViewProps {
  type: 'movie' | 'tv';
  id: string;
  season?: number;
  episode?: number;
  onClose?: () => void;
  initialProvider?: string;
  backdropUrl?: string;
}

export function VideoWebView({
  type,
  id,
  season,
  episode,
  onClose,
  initialProvider,
  backdropUrl,
}: VideoWebViewProps) {
  useKeepAwake();
  const insets = useSafeAreaInsets();
  const { height: SCREEN_HEIGHT, width: SCREEN_WIDTH } = Dimensions.get('window');
  const webViewRef = useRef<PlayerWebViewRef>(null);
  const providerHostRef = useRef<string>('');
  const navigationChainRef = useRef<Set<string>>(new Set());
  const pageLoadedRef = useRef(false);
  const navigationGenRef = useRef(0);
  const navigationAttemptsRef = useRef(0);
  const navigationReceivedRef = useRef(false);
  const progressRef = useRef<{ currentTime: number; duration: number; percent: number }>({ currentTime: 0, duration: 0, percent: 0 });
  const startAtRef = useRef<number>(0);
  const [startAtTime, setStartAtTime] = useState<number>(0);
  const lastSavePctRef = useRef<number>(0);
  const [loading, setLoading] = useState(true);
  const [slideInReady, setSlideInReady] = useState(false);
  useEffect(() => {
    const timer = setTimeout(() => setSlideInReady(true), 350);
    return () => clearTimeout(timer);
  }, []);
  const [error, setError] = useState<string | null>(null);
  const [showPicker, setShowPicker] = useState(false);
  const [auditMode, setAuditMode] = useState(false);
  const [auditHosts, setAuditHosts] = useState<string[]>([]);

  // â”€â”€ Overlay auto-hide (only in fullscreen) â”€â”€
  const overlayOpacity = useRef(new Animated.Value(1)).current;
  const hideTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [overlayVisible, setOverlayVisible] = useState(true);

  const scheduleHide = useCallback(() => {
    if (hideTimerRef.current) clearTimeout(hideTimerRef.current);
    hideTimerRef.current = setTimeout(() => {
      Animated.timing(overlayOpacity, {
        toValue: 0,
        duration: 300,
        useNativeDriver: true,
      }).start(() => setOverlayVisible(false));
    }, 3000);
  }, [overlayOpacity]);

  const showOverlay = useCallback(() => {
    setOverlayVisible(true);
    Animated.timing(overlayOpacity, {
      toValue: 1,
      duration: 200,
      useNativeDriver: true,
    }).start();
    scheduleHide();
  }, [overlayOpacity, scheduleHide]);

  const providers = useMemo(() => getEnabledProviders(), []);

  const [providerId, setProviderId] = useState<string>(
    initialProvider && providers.some((p) => p.id === initialProvider)
      ? initialProvider
      : providers[0]?.id ?? '',
  );
  const [isFullscreen, setIsFullscreen] = useState(false);

  useEffect(() => {
    if (isFullscreen) {
      ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE).catch(() => {});
      scheduleHide();
    } else {
      ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP).catch(() => {});
      if (hideTimerRef.current) clearTimeout(hideTimerRef.current);
      setOverlayVisible(true);
      Animated.timing(overlayOpacity, { toValue: 1, duration: 200, useNativeDriver: true }).start();
    }
    return () => { if (hideTimerRef.current) clearTimeout(hideTimerRef.current); };
  }, [isFullscreen, scheduleHide, overlayOpacity]);

  const orientationRestoredRef = useRef(false);
  const restorePortrait = useCallback(() => {
    if (orientationRestoredRef.current) return;
    orientationRestoredRef.current = true;
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP).catch(() => {});
  }, []);
  useEffect(() => {
    return () => { if (!orientationRestoredRef.current) { ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP).catch(() => {}); } };
  }, []);

  const [showEpPicker, setShowEpPicker] = useState(false);
  const [currentSeason, setCurrentSeason] = useState<number>(season ?? 1);
  const [currentEpisode, setCurrentEpisode] = useState<number>(episode ?? 1);

  // â”€â”€ Load watch history on mount to determine resume point â”€â”€
  const historyLoadedRef = useRef(false);
  useEffect(() => {
    if (historyLoadedRef.current) return;
    historyLoadedRef.current = true;
    (async () => {
      try {
        if (type === 'tv') {
          const resume = await getResumePoint(id, 'tv', currentSeason, currentEpisode);
          if (resume) {
            if (resume.season != null && resume.episode != null) {
              setCurrentSeason(resume.season);
              setCurrentEpisode(resume.episode);
            }
            if (resume.currentTime > 5 && !resume.completed) {
              startAtRef.current = resume.currentTime;
              setStartAtTime(resume.currentTime);
              if (pageLoadedRef.current) {
                seekTo(resume.currentTime);
              }
            }
          }
        } else {
          const progress = await getProgress(id, 'movie');
          if (progress && !progress.completed && progress.currentTime > 5) {
            startAtRef.current = progress.currentTime;
            setStartAtTime(progress.currentTime);
            if (pageLoadedRef.current) {
              seekTo(progress.currentTime);
            }
          }
        }
      } catch { /* silent */ }
    })();
  }, [type, id, currentSeason, currentEpisode]);

  const currentProvider = providers.find((p) => p.id === providerId);
  const isTV = type === 'tv';

  useEffect(() => {
    if (currentProvider) {
      try { providerHostRef.current = new URL(currentProvider.baseUrl).hostname; } catch (e) { providerHostRef.current = ''; }
    }
  }, [currentProvider]);

  useEffect(() => {
    navigationReceivedRef.current = false;
    const gen = navigationGenRef.current;
    const noNavTimer = setTimeout(() => { if (!navigationReceivedRef.current) { setLoading(false); } }, 30000);
    const safetyTimer = setTimeout(() => { setLoading(false); }, 35000);
    return () => { clearTimeout(noNavTimer); clearTimeout(safetyTimer); };
  }, [providerId, currentSeason, currentEpisode]);

  const watchUrl = useMemo(() => {
    if (!currentProvider) return '';
    const startAt = startAtTime > 0 ? startAtTime : undefined;
    const embedPath = type === 'tv' && currentSeason && currentEpisode
      ? currentProvider.embed.tv(id, currentSeason, currentEpisode, startAt)
      : currentProvider.embed.movie(id, startAt);
    return `${currentProvider.baseUrl}${embedPath}`;
  }, [currentProvider, type, id, currentSeason, currentEpisode, startAtTime]);

  const seekTo = useCallback((time: number) => {
    webViewRef.current?.injectJavaScript(`
      if (window.__playerSeek) { window.__playerSeek(${Math.floor(time)}, true); }
      true;
    `);
  }, []);

  const handleClose = useCallback(() => {
    restorePortrait();
    const prog = progressRef.current;
    if (prog.currentTime > 5) {
      saveProgress({
        tmdbId: id,
        mediaType: type,
        providerId,
        currentTime: prog.currentTime,
        duration: prog.duration,
        percent: prog.percent,
        season: isTV ? currentSeason : undefined,
        episode: isTV ? currentEpisode : undefined,
        updatedAt: Date.now(),
        completed: prog.percent >= 0.95,
      }).catch(() => {});
    }
    setTimeout(() => onClose?.(), 200);
  }, [restorePortrait, onClose, id, type, providerId, isTV, currentSeason, currentEpisode]);

  // â”€â”€ Periodic force-save (every 15s) â”€â”€
  useEffect(() => {
    const intervalId = setInterval(() => {
      const prog = progressRef.current;
      if (prog.currentTime > 5) {
        saveProgress({
          tmdbId: id,
          mediaType: type,
          providerId,
          currentTime: prog.currentTime,
          duration: prog.duration,
          percent: prog.percent,
          season: isTV ? currentSeason : undefined,
          episode: isTV ? currentEpisode : undefined,
          updatedAt: Date.now(),
          completed: prog.percent >= 0.95,
        }).catch(() => {});
      }
    }, 15000);
    return () => clearInterval(intervalId);
  }, [id, type, providerId, isTV, currentSeason, currentEpisode]);

  // â”€â”€ Save progress on unmount â”€â”€
  const unmountSavedRef = useRef(false);
  useEffect(() => {
    return () => {
      if (unmountSavedRef.current) return;
      unmountSavedRef.current = true;
      const prog = progressRef.current;
      if (prog.currentTime > 5) {
        saveProgress({
          tmdbId: id,
          mediaType: type,
          providerId,
          currentTime: prog.currentTime,
          duration: prog.duration,
          percent: prog.percent,
          season: isTV ? currentSeason : undefined,
          episode: isTV ? currentEpisode : undefined,
          updatedAt: Date.now(),
          completed: prog.percent >= 0.95,
        }).catch((err: unknown) => console.warn('Unmount save failed', err));
      }
    };
  }, [id, type, providerId, isTV, currentSeason, currentEpisode]);

  const switchProvider = async (newId: string) => {
    setLoading(true);
    setError(null);
    setShowPicker(false);
    navigationChainRef.current = new Set();
    pageLoadedRef.current = false;
    navigationGenRef.current += 1;
    navigationAttemptsRef.current = 0;
    const latestTime = (progressRef.current as any).currentTime ?? 0;
    if (latestTime > 5) { startAtRef.current = latestTime; setStartAtTime(latestTime); }

    // clearAllState is no longer needed — native destroys old WebView.
    // Keeping it as belt-and-suspenders for global CookieManager state.
    try {
      await clearAllState();
    } catch {
      // State clearing is best-effort; proceed anyway
    }
    setProviderId(newId);
    // mountGen bump REMOVED — native handles switch via double-buffering
    // watchUrl recomputes → sourceUri setter → native switchProvider()
  };

  const [mountGen, setMountGen] = useState(0);
  const webViewKey = `player-${mountGen}`;

  const getProviderDisplayName = (p: ProviderDefinition): string => p.displayName || p.name || p.id;

  const retry = () => {
    if (error) { setError(null); setLoading(true); }
    navigationAttemptsRef.current = 0;
    setMountGen((g) => g + 1);
  };

  if (error) {
    return (
      <View className="flex-1 items-center justify-center bg-zinc-950 px-8">
        <View className="w-16 h-16 rounded-full bg-red-500/10 items-center justify-center mb-5">
          <Ionicons name="alert-circle" size={32} color="#ef4444" />
        </View>
        <Text className="text-zinc-300 text-lg font-semibold mb-2">Playback Error</Text>
        <Text className="text-zinc-500 text-sm mb-8 text-center leading-5">{error}</Text>
        <View className="flex-row gap-3">
          <TouchableOpacity onPress={retry} className="bg-primary rounded-xl py-3 px-6 flex-row items-center" activeOpacity={0.8}>
            <Ionicons name="refresh" size={16} color="#000" />
            <Text className="text-black font-bold text-sm ml-2">Retry</Text>
          </TouchableOpacity>
          <TouchableOpacity onPress={() => setShowPicker(true)} className="bg-zinc-800 rounded-xl py-3 px-6 flex-row items-center" activeOpacity={0.8}>
            <Ionicons name="server" size={16} color="#d4d4d8" />
            <Text className="text-zinc-300 font-bold text-sm ml-2">Switch Server</Text>
          </TouchableOpacity>
        </View>
        <ServerPickerSheet
          visible={showPicker}
          providers={providers}
          currentId={providerId}
          onSelect={switchProvider}
          onClose={() => setShowPicker(false)}
          getDisplayName={getProviderDisplayName}
        />
      </View>
    );
  }

  // â”€â”€ Empty URL guard â”€â”€
  if (!watchUrl) {
    return (
      <View className="flex-1 items-center justify-center bg-black px-8">
        <View className="w-16 h-16 rounded-full bg-zinc-800 items-center justify-center mb-5">
          <Ionicons name="server" size={28} color="#52525B" />
        </View>
        <Text className="text-zinc-300 text-lg font-semibold mb-2">No player available</Text>
        <Text className="text-zinc-500 text-sm mb-8 text-center leading-5">
          No streaming servers are available. Try selecting a different server.
        </Text>
        <TouchableOpacity onPress={() => setShowPicker(true)} className="bg-primary rounded-xl py-3 px-6 flex-row items-center" activeOpacity={0.8}>
          <Ionicons name="server" size={16} color="#000" />
          <Text className="text-black font-bold text-sm ml-2">Choose Server</Text>
        </TouchableOpacity>
        <ServerPickerSheet
          visible={showPicker}
          providers={providers}
          currentId={providerId}
          onSelect={switchProvider}
          onClose={() => setShowPicker(false)}
          getDisplayName={getProviderDisplayName}
        />
      </View>
    );
  }

  return (
    <View className="flex-1 bg-black">
      {/* â”€â”€ Controls overlay â”€â”€ */}
      <PlayerControlOverlay
        isFullscreen={isFullscreen}
        isTV={isTV}
        loading={loading}
        overlayVisible={overlayVisible}
        showOverlay={showOverlay}
        overlayOpacity={overlayOpacity}
        onClose={handleClose}
        onToggleFullscreen={() => setIsFullscreen((f) => !f)}
        onServerPickerOpen={() => setShowPicker(true)}
        onEpisodePickerOpen={() => { setShowEpPicker(true); }}
        currentSeason={currentSeason}
        currentEpisode={currentEpisode}
        providerDisplayName={currentProvider ? getProviderDisplayName(currentProvider) : 'Server'}
        providerId={providerId}
        auditMode={auditMode}
      />

      {/* â”€â”€ Server picker modal â”€â”€ */}
      <ServerPickerSheet
        visible={showPicker}
        providers={providers}
        currentId={providerId}
        onSelect={switchProvider}
        onClose={() => setShowPicker(false)}
        getDisplayName={getProviderDisplayName}
      />

      {/* â”€â”€ Episode picker modal (TV only) â”€â”€ */}
      {isTV && (
        <EpisodeRail
          visible={showEpPicker}
          tvId={id}
          currentSeason={currentSeason}
          currentEpisode={currentEpisode}
          onSelect={(s, e) => {
            setCurrentSeason(s);
            setCurrentEpisode(e);
            setShowEpPicker(false);
            if (s !== currentSeason || e !== currentEpisode) {
              setMountGen((g) => g + 1);
              setLoading(true);
            }
          }}
          onClose={() => setShowEpPicker(false)}
        />
      )}

      {/* â”€â”€ Audit Results Modal â”€â”€ */}
      <Modal visible={auditHosts.length > 0 && !auditMode} transparent animationType="fade" onRequestClose={() => setAuditHosts([])}>
        <View className="flex-1 bg-black/70 items-center justify-center px-6">
          <View className="bg-zinc-900 rounded-2xl w-full max-h-[60%] p-5 border border-zinc-800">
            <View className="flex-row items-center justify-between mb-4">
              <View className="flex-row items-center gap-2">
                <Ionicons name="radio-outline" size={18} color="#D4A237" />
                <Text className="text-white text-lg font-bold">Discovered Domains</Text>
              </View>
              <TouchableOpacity onPress={() => setAuditHosts([])} activeOpacity={0.7} accessibilityLabel="Close audit results" accessibilityRole="button">
                <Ionicons name="close" size={20} color="#71717a" />
              </TouchableOpacity>
            </View>
            <Text className="text-zinc-400 text-xs mb-3">
              {auditHosts.length} unique hosts captured during this session.
            </Text>
            <ScrollView className="flex-1" showsVerticalScrollIndicator={false}>
              {auditHosts.map((host, i) => (
                <View key={host} className="flex-row items-center py-2 px-3 rounded-lg mb-1 bg-zinc-800/50">
                  <Text className="text-zinc-300 text-xs font-mono flex-1">{host}</Text>
                </View>
              ))}
            </ScrollView>
            <TouchableOpacity
              onPress={() => { console.warn(`[Audit] JSON:\n${JSON.stringify(auditHosts, null, 2)}`); setAuditHosts([]); }}
              className="bg-primary rounded-xl py-3 mt-4 items-center"
              activeOpacity={0.8}
            >
              <Text className="text-black font-bold text-sm">Export & Close</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>

      {/* â”€â”€ Player area â”€â”€ */}
      <View
        style={!isFullscreen
          ? { height: providerId === 'nxsha' ? SCREEN_HEIGHT * 0.40 : SCREEN_HEIGHT * 0.68, justifyContent: 'center', marginTop: insets.top + 40 }
          : { flex: 1 }
        }
      >
        {backdropUrl && loading && (
          <Image
            source={{ uri: getImageUrl(backdropUrl, 'w780') }}
            style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 }}
            resizeMode="cover"
            blurRadius={Platform.OS === 'android' ? 10 : 20}
          />
        )}
        <View style={!isFullscreen ? { width: '100%', height: '100%', backgroundColor: '#000' } : { flex: 1 }}>
          <PlayerWebView
            key={webViewKey}
            ref={webViewRef}
            source={{ uri: slideInReady ? watchUrl : '' }}
            style={{ width: '100%', height: '100%', backgroundColor: '#000' }}
            allowsFullscreenVideo={true}
            injectedJavaScriptBeforeContentLoaded={
              currentProvider?.baseUrl
                ? makeConsolidatedScript(new URL(currentProvider.baseUrl).hostname, currentProvider.id)
                : ''
            }
            referrer={currentProvider?.baseUrl || ''}
            setSupportMultipleWindows={false}
            javaScriptCanOpenWindowsAutomatically={false}
            auditMode={auditMode}
            onAuditData={(event) => {
              const { hosts: hostsStr } = event.nativeEvent;
              const domains = hostsStr ? hostsStr.split(',').filter(Boolean) : [];
              setAuditHosts(domains);
            }}
            userAgent="Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.165 Mobile Safari/537.36"
            onLoadingStart={(event) => {
              navigationReceivedRef.current = true;
            }}
            onLoadingFinish={(event) => {
              setLoading(false);
              const gen = navigationGenRef.current;
              setTimeout(() => {
                if (navigationGenRef.current === gen && !pageLoadedRef.current) {
                  pageLoadedRef.current = true;
                }
              }, 15000);
              const seekTime = startAtRef.current;
              if (seekTime > 5) {
                seekTo(seekTime);
                startAtRef.current = 0;
              }
            }}
            onHttpError={(syntheticEvent) => {
              const err = syntheticEvent.nativeEvent;
              setLoading(false);
              if (err.statusCode === 403 && providerId === 'toustream') {
                setError('Server 19 is behind Cloudflare protection and cannot be accessed directly. Please try a different server.');
              }
            }}
            onRenderProcessGone={() => {
              setLoading(true);
              setMountGen((g) => g + 1);
            }}
            onMessage={(event) => {
              try {
                const data = JSON.parse(event.nativeEvent.data);
                if (data.type === '__diag' || data.type === 'player:diag') {
                  return;
                }
                if (data.type === 'cf:content-ready') {
                  setLoading(false);
                  navigationReceivedRef.current = true;
                  pageLoadedRef.current = true;
                  const seekTime = startAtRef.current;
                  if (seekTime > 5) { seekTo(seekTime); startAtRef.current = 0; }
                  return;
                }
                if (data.type === 'cf:fullscreen') {
                  if (data.entering) {
                    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE).catch(() => {});
                    setOverlayVisible(false);
                    overlayOpacity.setValue(0);
                  } else {
                    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP).catch(() => {});
                    setOverlayVisible(true);
                    Animated.timing(overlayOpacity, { toValue: 1, duration: 200, useNativeDriver: true }).start();
                  }
                  return;
                }
                if (data.type === 'console') {
                  const level = data.level || 'log';
                  const args = data.args || [];
                  const text = args.join(' ');
                  if (level === 'error' || level === 'warn') {
                    console.warn(`[Page:${level.toUpperCase()}] ${text}`);
                  }
                  return;
                }
                if (data.type === 'player:progress' || data.type === 'screenscape:progress') {
                  const { currentTime = 0, duration = 0, percent: pct = 0 } = data.data ?? {};
                  const newPct = duration > 0 ? currentTime / duration : pct;
                  const prevPct = progressRef.current.percent;
                  if (newPct >= prevPct) {
                    progressRef.current = { currentTime, duration, percent: newPct };
                  }
                  if (currentTime > 5) {
                    const pctDiff = newPct - lastSavePctRef.current;
                    if (pctDiff >= 0.05 || newPct >= 0.95) {
                      lastSavePctRef.current = newPct;
                      saveProgress({
                        tmdbId: id,
                        mediaType: type,
                        providerId,
                        currentTime,
                        duration,
                        percent: newPct,
                        season: isTV ? currentSeason : undefined,
                        episode: isTV ? currentEpisode : undefined,
                        updatedAt: Date.now(),
                        completed: newPct >= 0.95,
                      }).catch(() => {});
                    }
                  }
                  if (isTV && prevPct < 0.95 && newPct >= 0.95) {
                    markCompleted(id, 'tv', currentSeason, currentEpisode).catch(() => {});
                  }
                }
              } catch(e) {}
            }}
          />
        </View>
      </View>
    </View>
  );
}
