/**
 * CSP Builder — generates per-provider Content-Security-Policy headers
 * driven by the provider's `allowedOrigins` config.
 *
 * Without `allowedOrigins`, returns a permissive policy (everything
 * allowed — for maximum compatibility with unknown provider origins).
 * With `allowedOrigins`, tightens specific directives to only allow
 * known-good origins, reducing the attack surface for script injection
 * and data exfiltration.
 */

import type { ProviderDefinition } from '@filmsnaps/shared';

/**
 * Build a Content-Security-Policy header string for a given provider.
 *
 * @param provider - The provider definition (uses allowedOrigins if set)
 * @param nonce - Optional nonce for inline scripts (autogenerated if omitted)
 * @param extraOrigins - Additional origins to permit (e.g., the provider's
 *   baseUrl host, CDNs discovered at runtime)
 */
export function buildProviderCSP(
  provider: ProviderDefinition,
  nonce?: string,
  extraOrigins: string[] = [],
): string {
  // Collect all origins from provider config + extra origins
  const origins = new Set([
    ...(provider.allowedOrigins ?? []),
    ...extraOrigins,
    // Always allow the provider's base URL origin
    ...extractOrigin(provider.baseUrl),
  ]);

  // Deduplicated, sorted for deterministic output
  const sorted = Array.from(origins).sort();

  // Without any origins, return permissive policy (full compatibility)
  if (sorted.length === 0) {
    return `default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; form-action 'none'; navigate-to 'none';`;
  }

  const originsStr = sorted.join(' ');

  // With origins, tighten the meaningful directives
  const parts: string[] = [];

  // Script: self + allowed origins + unsafe-inline (most providers need it)
  parts.push(`script-src 'self' 'unsafe-inline' 'unsafe-eval' ${originsStr}`);

  // Style: self + unsafe-inline for injected CSS
  parts.push(`style-src 'self' 'unsafe-inline' ${originsStr}`);

  // Media: permissive over https for video chunks
  parts.push(`media-src 'self' data: blob: https: ${originsStr}`);

  // Frame: restrict to allowed origins only
  parts.push(`frame-src 'self' ${originsStr}`);

  // Connect: restrict fetch/XHR/WebSocket
  parts.push(`connect-src 'self' ${originsStr}`);

  // Images: self + data + blob + allowed origins
  parts.push(`img-src 'self' data: blob: https: ${originsStr}`);

  // Fonts: self + data + allowed origins (for provider-specific fonts)
  parts.push(`font-src 'self' data: ${originsStr}`);

  // Workers: self + blob
  parts.push(`worker-src 'self' blob:`);

  // Hardened directives
  parts.push('default-src *'); // catch-all fallback
  parts.push('object-src \'none\'');
  parts.push('base-uri \'self\'');
  parts.push('form-action \'self\'');

  return parts.join('; ');
}

/**
 * Build a Content-Security-Policy string for the `<iframe csp="...">`
 * attribute — enforced by the parent page on a cross-origin iframe.
 *
 * This is a browser-level enforcement layer that works WITHOUT a proxy.
 * It blocks:
 *  - Crypto miners (worker-src 'none')
 *  - Tracking beacons (restricted connect-src)
 *  - Plugin-based ads (object-src 'none')
 *
 * While allowing:
 *  - Script execution (providers need JS)
 *  - Video/media from any HTTPS source
 *  - Images from any HTTPS source
 *
 * @param provider - Provider definition (uses allowedOrigins for connect-src)
 */
export function buildIframeCSP(provider: ProviderDefinition): string {
  const origins = new Set([
    ...(provider.allowedOrigins ?? []),
    ...extractOrigin(provider.baseUrl),
  ]);
  const originsStr = Array.from(origins).sort().join(' ');

  const parts: string[] = [];

  // Base lockdown — deny everything by default
  parts.push("default-src 'none'");

  // Scripts: providers need JS to render video players
  parts.push("script-src 'unsafe-inline' 'unsafe-eval'");

  // Workers: blocked — crypto miners and heavy ad scripts need workers
  parts.push("worker-src 'none'");

  // Network requests: restricted to self + known CDNs
  if (originsStr) {
    parts.push(`connect-src 'self' ${originsStr}`);
  } else {
    parts.push("connect-src 'self'");
  }

  // Video/audio: permissive over HTTPS (video chunks come from various CDNs)
  parts.push('media-src \'self\' blob: https:');

  // Images: provider UI needs images
  parts.push('img-src \'self\' data: https:');

  // Styles: providers need inline styles
  parts.push("style-src 'unsafe-inline'");

  // Fonts: allow self + data URIs
  parts.push("font-src 'self' data: https:");

  // Objects/flash: blocked
  parts.push("object-src 'none'");

  // Frames: restrict to none (prevents nested ad iframes)
  // But allow the provider's own frames if needed
  if (originsStr) {
    parts.push(`frame-src ${originsStr}`);
  } else {
    parts.push('frame-src \'none\'');
  }

  return parts.join('; ');
}

/**
 * Extract the origin(s) from a base URL.
 * For example, "https://peachify.top/embed" → ["https://peachify.top"]
 * Handles malformed URLs gracefully (returns empty array).
 */
function extractOrigin(baseUrl: string): string[] {
  try {
    const url = new URL(baseUrl);
    return [url.origin];
  } catch {
    return [];
  }
}
